"""TEST_ONLY public rotated boxes generated by the exact pinned FreeCAD worker.

This acceptance input creates no Core/solver/provider operation and never edits
an existing source. Production catalog capture is tested separately against its
retained native exports. All request paths are supplied by the owned test runner.
"""

import importlib.util
import json
import os
from pathlib import Path
import sys


def launch(request):
    environment = {**os.environ, "CAELAB_FACE_TEST_REQUEST": str(request),
                   "CAELAB_FACE_TEST_WORKER": str(Path(__file__).resolve())}
    command = os.environ["FREECAD_CMD"]
    os.execvpe(command, [command, str(Path(__file__).resolve())], environment)


def generate():
    import FreeCAD as App

    request_path = Path(os.environ["CAELAB_FACE_TEST_REQUEST"])
    request = json.loads(request_path.read_text())
    source = Path(request["source"])
    output = Path(request["output"])
    upstream = Path(request["repo"]) / "plugins/fixture_design/upstream/fixturelab/freecad_worker.py"
    spec = importlib.util.spec_from_file_location("caelab_pinned_box_acceptance_worker", upstream)
    worker = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(worker)
    catalog_spec = importlib.util.spec_from_file_location("caelab_catalog_native_refusal_probe",
        Path(request["repo"]) / "caelab/adapters/freecad_face_catalog_worker.py")
    catalog_worker = importlib.util.module_from_spec(catalog_spec)
    catalog_spec.loader.exec_module(catalog_worker)
    if source.exists() or output.exists():
        raise ValueError("Test fixture paths must be fresh")
    document = App.newDocument("NativeCatalogPublicBox")
    try:
        box = document.addObject("Part::Box", "Box")
        box.Label = "Public synthetic rotated box"
        box.Length = request["length_mm"]
        box.Width = 8
        box.Height = 5
        box.Placement = App.Placement(App.Vector(-7, 2, 3), App.Rotation(App.Vector(0, 0, 1), 30))
        worker._save_registry(document, {"parameters": [], "final": box.Name})
        document.recompute()
        geometry = box.Shape.copy()
        refusal_probes = {}
        for name, bad_shape in (("isolated_vertex", worker.Part.makeCompound(
                [geometry, worker.Part.Vertex(App.Vector(99, 99, 99))])),
                ("multiple_solids", worker.Part.makeCompound([geometry, worker.Part.makeBox(1, 1, 1)]))):
            try:
                catalog_worker._solid(bad_shape, "Test-only unsupported geometry")
            except ValueError:
                refusal_probes[name] = True
            else:
                raise ValueError("Unsupported native geometry was admitted: " + name)
        document.saveAs(str(source))
    finally:
        App.closeDocument(document.Name)
    raw = worker.dispatch({"action": "generate", "document": str(source), "values": {}, "output": str(output)})
    if raw["decision"] != "REVIEW_REQUIRED":
        raise ValueError("Pinned public box generation failed")
    # Isolated native fixture metadata, not a claim of Core/export qualification.
    (output / "result.json").write_text(json.dumps({"cad_generated": True,
        "decision": raw["decision"], "bom": [{"volume_mm3": raw["volume_mm3"]}],
        "bounds_mm": raw["bounds_mm"], "test_only": True, "native_refusal_probes": refusal_probes}), encoding="utf-8")


if __name__ == "__main__":
    if len(sys.argv) == 3 and sys.argv[1] == "--launch":
        launch(Path(sys.argv[2]).resolve())
    else:
        generate()
