"""Independent known-number checks for the fixture-free elasticity plugin."""

import copy
import json
import math

import pytest

from plugins.elasticity import analytical_reference, assess, displacement_at, model_declaration, validate_settings


def _settings():
    return {"case": "uniaxial_block", "dimensions_mm": [10, 4, 2],
            "material": {"youngs_modulus_mpa": 1000, "poisson_ratio": 0.25},
            "traction_mpa": 2, "mesh_sizes_mm": [1, 0.5],
            "limits": {"displacement_relative": 1e-8, "displacement_absolute_mm": 1e-12,
                       "stress_relative": 1e-8, "reaction_relative": 1e-8,
                       "mesh_agreement_relative": 1e-8}}


# Explicit known values, not generated by the implementation under test:
# strain=[.002,-.0005,-.0005], sigma_xx=2 MPa, F_x=-16 N, energy=.16 N mm.
_COORDS = [[0, 0, 0], [10, 0, 0], [0, 4, 0], [10, 4, 0],
           [0, 0, 2], [10, 0, 2], [0, 4, 2], [10, 4, 2], [5, 2, 1]]
_DISPLACEMENTS = [[0, 0, 0], [0.02, 0, 0], [0, -0.002, 0], [0.02, -0.002, 0],
                  [0, 0, -0.001], [0.02, 0, -0.001], [0, -0.002, -0.001],
                  [0.02, -0.002, -0.001], [0.01, -0.001, -0.0005]]


def _records():
    return [{"mesh_size_mm": size, "node_ids": list(range(1, 10)),
             "coordinates_mm": copy.deepcopy(_COORDS),
             "displacements_mm": copy.deepcopy(_DISPLACEMENTS),
             "stresses_mpa": [[2, 0, 0, 0, 0, 0], [2, 0, 0, 0, 0, 0]],
             "reaction_n": [-16, 0, 0], "element_count": 2} for size in [1, 0.5]]


def test_exact_physical_reference_including_poisson_and_signed_reaction():
    result = analytical_reference(_settings())
    assert result["axial_tip_displacement_mm"] == pytest.approx(0.02)
    assert result["transverse_tip_displacements_mm"] == pytest.approx([-0.002, -0.001])
    assert result["stress_components_mpa"] == [2, 0, 0, 0, 0, 0]
    assert result["stress_component_order"] == ["xx", "yy", "zz", "xy", "xz", "yz"]
    assert result["reaction_n"] == [-16, 0, 0]
    assert result["strain_energy_n_mm"] == pytest.approx(0.16)
    observed = displacement_at(copy.deepcopy(_COORDS), _settings())
    for actual, expected in zip(observed, _DISPLACEMENTS):
        assert actual == pytest.approx(expected, abs=1e-16)


def test_exact_observations_pass_and_axial_response_is_not_displacement_magnitude():
    result = assess(_settings(), _records())
    assert [check["code"] for check in result["checks"]] == [
        "analytical_displacement", "analytical_stress", "signed_reaction_balance", "mesh_agreement"]
    assert all(check["status"] == "PASS" for check in result["checks"])
    assert all(metric["valid"] for metric in result["metrics"].values())
    assert result["metrics"]["axial_tip_displacement"]["value"] == pytest.approx(0.02)
    assert result["metrics"]["axial_tip_displacement"]["unit"] == "mm"
    assert result["metrics"]["axial_tip_displacement"]["value"] != pytest.approx(
        math.sqrt(0.02**2 + 0.002**2 + 0.001**2), abs=1e-8)
    assert result["metrics"]["stress_relative_error"]["value"] == 0.0
    assert result["metrics"]["reaction_x"]["value"] == -16
    assert result["metrics"]["reaction_x"]["unit"] == "N"
    assert result["metrics"]["mesh_agreement_relative"]["value"] == 0.0
    assert set(result["pending_validations"]) == {"static_strength", "material_qualification",
        "physical_validation", "fatigue_durability", "model_qualification"}
    assert not any("rate" in key for key in result["metrics"])
    json.dumps(result, allow_nan=False)


@pytest.mark.parametrize("field,offset,expected_check", [
    ("displacements_mm", (8, 1, 1e-5), "analytical_displacement"),
    ("stresses_mpa", (1, 0, 0.01), "analytical_stress"),
    ("stresses_mpa", (1, 4, 0.01), "analytical_stress"),
    ("reaction_n", (0, None, 0.1), "signed_reaction_balance"),
    ("reaction_n", (1, None, 0.1), "signed_reaction_balance"),
])
def test_perturbed_observations_fail_and_keep_invalid_numerical_metrics(field, offset, expected_check):
    records = _records()
    row, column, change = offset
    if column is None:
        records[0][field][row] += change
    else:
        records[0][field][row][column] += change
    result = assess(_settings(), records)
    assert next(check for check in result["checks"] if check["code"] == expected_check)["status"] == "FAIL"
    assert all(not metric["valid"] and expected_check in metric["reason"]
               for metric in result["metrics"].values())
    assert all(metric["value"] is not None for metric in result["metrics"].values())
    json.dumps(result, allow_nan=False)


def test_mesh_agreement_compares_signed_right_face_dx():
    records = _records()
    for index in [1, 3, 5, 7]:
        records[0]["displacements_mm"][index][0] += 1e-5
    result = assess(_settings(), records)
    check = next(item for item in result["checks"] if item["code"] == "mesh_agreement")
    assert check["status"] == "FAIL"
    assert check["observed"] == pytest.approx(0.0005)
    assert result["metrics"]["mesh_axial_displacement_difference"]["value"] == pytest.approx(1e-5)
    assert result["metrics"]["axial_tip_displacement"]["value"] == pytest.approx(0.02)
    assert result["mesh_response"]["component"] == "DX"


def test_displacement_uses_declared_absolute_plus_global_relative_scale():
    settings = _settings()
    settings["limits"]["displacement_absolute_mm"] = 1e-5
    records = _records()
    records[0]["displacements_mm"][8][1] += 9e-6
    result = assess(settings, records)
    check = next(item for item in result["checks"] if item["code"] == "analytical_displacement")
    assert check["status"] == "PASS"
    assert check["limit"]["global_reference_scale_mm"] == pytest.approx(0.02)
    assert check["limit"]["combined_absolute_mm"] == pytest.approx(1e-5 + 1e-8 * 0.02)
    assert result["metrics"]["max_component_displacement_error"]["value"] == pytest.approx(9e-6)
    assert result["metrics"]["displacement_relative_error"]["value"] == pytest.approx(0.00045)


def test_inputs_and_returned_settings_are_independent():
    settings, records = _settings(), _records()
    before_settings, before_records = copy.deepcopy(settings), copy.deepcopy(records)
    normalized = validate_settings(settings)
    assess(settings, records)
    displacement_at(records[0]["coordinates_mm"], settings)
    analytical_reference(settings)
    declaration = model_declaration(settings)
    assert settings == before_settings and records == before_records
    normalized["dimensions_mm"][0] = 99
    normalized["material"]["youngs_modulus_mpa"] = 99
    normalized["limits"]["stress_relative"] = 99
    declaration["geometry"]["dimensions_mm"][0] = 99
    declaration["materials"][0]["youngs_modulus"]["value"] = 99
    declaration["mesh"]["sizes_mm"][0] = 99
    assert settings == before_settings


def test_domain_model_declaration_contains_typed_physics_without_solver_syntax():
    declaration = model_declaration(_settings())
    assert declaration["geometry"] == {"type": "block", "dimensions_mm": [10, 4, 2],
                                        "unit": "mm", "origin": [0, 0, 0]}
    assert declaration["materials"][0]["youngs_modulus"] == {"value": 1000, "unit": "MPa"}
    assert declaration["materials"][0]["poisson_ratio"] == {"value": 0.25, "unit": "1"}
    assert declaration["mesh"] == {"sizes_mm": [1, 0.5], "order": 2, "element_type": "TETRA10"}
    assert [(item["selection"]["axis"], item["selection"]["coordinate_mm"], item["component"], item["value"])
            for item in declaration["boundary_conditions"]] == [("x", 0, "x", 0),
                                                               ("y", 0, "y", 0), ("z", 0, "z", 0)]
    assert declaration["loads"] == [{"type": "traction",
                                     "selection": {"type": "plane", "axis": "x", "coordinate_mm": 10},
                                     "value": [2, 0, 0], "unit": "MPa"}]
    assert [item["field"] for item in declaration["outputs"]["fields"]] == ["displacement", "stress", "reactions"]
    json.dumps(declaration, allow_nan=False)


@pytest.mark.parametrize("path,value", [
    (("case",), "fixture"), (("dimensions_mm",), [10, 4]), (("dimensions_mm",), [10, 4, 2, 1]),
    (("dimensions_mm",), [10, 4, 0]), (("dimensions_mm",), [10, -4, 2]),
    (("dimensions_mm",), [10, True, 2]), (("dimensions_mm",), [10, math.inf, 2]),
    (("dimensions_mm",), [10, math.nan, 2]), (("dimensions_mm",), (10, 4, 2)),
    (("material", "youngs_modulus_mpa"), 0), (("material", "youngs_modulus_mpa"), -1),
    (("material", "youngs_modulus_mpa"), True), (("material", "youngs_modulus_mpa"), math.inf),
    (("material", "poisson_ratio"), -1), (("material", "poisson_ratio"), 0.5),
    (("material", "poisson_ratio"), math.nan), (("material", "poisson_ratio"), False),
    (("traction_mpa",), 0), (("traction_mpa",), -2), (("traction_mpa",), True),
    (("traction_mpa",), math.inf), (("mesh_sizes_mm",), [1]),
    (("mesh_sizes_mm",), [1, .75, .5, .25]), (("mesh_sizes_mm",), [1, 1]),
    (("mesh_sizes_mm",), [.5, 1]), (("mesh_sizes_mm",), [3, 1]),
    (("mesh_sizes_mm",), [1, 0]), (("mesh_sizes_mm",), [1, True]),
    (("mesh_sizes_mm",), [1, math.nan]), (("limits", "stress_relative"), 0),
    (("limits", "displacement_relative"), -1), (("limits", "reaction_relative"), math.inf),
    (("limits", "displacement_absolute_mm"), True),
])
def test_bad_settings_fail_preflight(path, value):
    settings = _settings()
    parent = settings
    for key in path[:-1]:
        parent = parent[key]
    parent[path[-1]] = value
    with pytest.raises(ValueError):
        validate_settings(settings)


@pytest.mark.parametrize("section", [None, "material", "limits"])
@pytest.mark.parametrize("change", ["missing", "extra"])
def test_unknown_or_missing_public_keys_are_rejected(section, change):
    settings = _settings()
    value = settings if section is None else settings[section]
    if change == "extra":
        value["solver_path"] = "unrequested"
    else:
        value.pop(next(iter(value)))
    with pytest.raises(ValueError):
        validate_settings(settings)


def test_unrepresentable_analytical_reference_is_rejected_before_solver():
    settings = _settings()
    settings["material"]["youngs_modulus_mpa"] = 1e-308
    settings["traction_mpa"] = 1e308
    with pytest.raises(ValueError, match="Analytical strain"):
        validate_settings(settings)


@pytest.mark.parametrize("mutation", [
    lambda r: r.pop(), lambda r: r[0].pop("reaction_n"),
    lambda r: r[0].update(mesh_size_mm=0.75),
    lambda r: r[0].update(node_ids=[1] * 9),
    lambda r: r[0]["node_ids"].__setitem__(0, True),
    lambda r: r[0]["coordinates_mm"].pop(), lambda r: r[0]["displacements_mm"].pop(),
    lambda r: r[0]["coordinates_mm"].__setitem__(0, [0, 0]),
    lambda r: r[0]["coordinates_mm"][0].__setitem__(0, -1),
    lambda r: r[0]["coordinates_mm"][0].__setitem__(0, math.nan),
    lambda r: r[0]["displacements_mm"][0].__setitem__(0, math.inf),
    lambda r: r[0]["displacements_mm"][0].__setitem__(0, True),
    lambda r: r[0].update(stresses_mpa=[]),
    lambda r: r[0].update(stresses_mpa=[[2, 0, 0, 0, 0, 0]]),
    lambda r: r[0]["stresses_mpa"][0].pop(),
    lambda r: r[0]["stresses_mpa"][1].__setitem__(5, math.nan),
    lambda r: r[0].update(reaction_n=[-16, 0]),
    lambda r: r[0].update(reaction_n=[-16, 0, math.inf]),
    lambda r: r[0].update(element_count=0), lambda r: r[0].update(element_count=True),
])
def test_malformed_or_incomplete_mesh_observations_raise(mutation):
    records = _records()
    mutation(records)
    with pytest.raises(ValueError):
        assess(_settings(), records)


@pytest.mark.parametrize("coords", [[], [[0, 0]], [[0, 0, True]], [[0, 0, math.inf]], [[11, 0, 0]]])
def test_analytical_field_rejects_malformed_or_outside_coordinates(coords):
    with pytest.raises(ValueError):
        displacement_at(coords, _settings())
