/* Design review prototype. File persistence is server-side; all calculations and generated replies are labeled demonstrations. */
(() => {
  'use strict';
  const APP = document.body.dataset.app;
  const META = {
    pre: {name:'전처리', sub:'데이터 · 영역 · 조건', icon:'◇'},
    runner: {name:'솔버 실행기', sub:'케이스 · 실행 이력', icon:'▷'},
    post: {name:'후처리', sub:'필드 · 이력 · 비교', icon:'▥'},
    opt: {name:'최적화', sub:'절차 · 설계 공간', icon:'⬡'},
    expert: {name:'전문가 자문', sub:'대화 · 근거 · 논점', icon:'◎'},
    workbench: {name:'Workbench', sub:'프로젝트 · 버전 연결', icon:'▦'}
  };
  const el = id => document.getElementById(id);
  const s = {doc:null, docs:[], selection:'', view:'', dirty:false, readOnly:false, undo:[], notice:'', issue:'', openIds:[], live:{}, menu:null};
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clone = v => structuredClone(v);
  const id = prefix => prefix + Math.random().toString(36).slice(2,9);
  const fmt = n => Number.isFinite(Number(n)) ? Number(n).toLocaleString('ko-KR',{maximumFractionDigits:3}) : '—';
  const btn = (label, act, extra='') => `<button data-act="${act}" ${extra}>${label}</button>`;
  const pill = (t, type='') => `<span class="pill ${type}">${esc(t)}</span>`;
  const note = (msg, type='') => `<div class="notice ${type}">${msg}</div>`;
  const row = (label,value) => `<div class="property-row"><span>${esc(label)}</span><b>${esc(value)}</b></div>`;
  const field = (label,path,value,type='text',opts='') => `<label>${esc(label)}<input data-field="${esc(path)}" type="${type}" value="${esc(value)}" ${opts}></label>`;
  const select = (label,path,value,options) => `<label>${esc(label)}<select data-field="${esc(path)}">${options.map(o=>`<option value="${esc(o)}" ${o===value?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`;
  const tree = (label,key,symbol='◇',count='') => `<button class="${s.selection===key?'active':''}" data-select="${esc(key)}" title="${esc(label)}"><span class="symbol">${symbol}</span><span>${esc(label)}</span>${count!==''?`<span class="count">${count}</span>`:''}</button>`;
  const group = label => `<div class="group">${esc(label)}</div>`;

  async function api(path, options) {
    const response = await fetch(path, options);
    const value = await response.json();
    if (!response.ok) { const error = new Error(value.error || response.statusText); error.status=response.status; error.value=value; throw error; }
    return value;
  }
  function notify(message, issue='') { s.notice=message; s.issue=issue; renderStatus(); renderDock(); }
  function failure(error) { notify(error.message || String(error), 'bad'); }
  async function loadList() {
    try { s.docs=(await api('/api/docs')).docs; render(); }
    catch(error) { failure(error); }
  }
  function initial(kind) {
    const base={schemaVersion:1, provenance:'Design Lab example', views:{}};
    if(kind==='pre') return {...base, mode:'curve', source:'예시 곡선 · 시안', unitX:'s',unitY:'MPa', points:[[0,0],[.2,.18],[.4,.41],[.6,.57],[.8,.64],[1,.68]], intervals:[{id:'seg-1',name:'동정 구간',start:.2,end:.8,weight:1}], material:{name:'시편 A',law:'선형 탄성',E:1000,nu:.3}, conditions:[{id:'cond-1',name:'시험 속도',target:'seg-1',value:1,unit:'mm/s'}], mesh:[], field:null};
    if(kind==='runner') return {...base, cases:[{id:'case-1',name:'시편 A · 평가',sourceId:'',sourceRevision:0,backend:'시연 계산기',valid:true}], runs:[], selectedRun:'', resources:{threads:1}};
    if(kind==='post') return {...base, datasets:[{id:'result-1',name:'예시 결과',source:'시안 내장',kind:'field',unit:'MPa',frames:[0,1,2],values:[[.12,.25,.33,.19,.47,.55,.28,.37,.61,.32,.49,.72],[.2,.34,.48,.35,.61,.69,.42,.58,.77,.49,.65,.9],[.27,.42,.57,.46,.72,.8,.53,.69,.88,.59,.78,1]],curve:[[0,.12],[1,.2],[2,.27]]}], selectedDataset:'result-1',frame:1,component:'σxx',location:0,legendMin:0,legendMax:1,compareId:''};
    if(kind==='opt') return {...base, nodes:[{id:'source',type:'입력',x:10,y:41},{id:'evaluate',type:'평가기',x:37,y:41},{id:'objective',type:'목적',x:67,y:41}],edges:[['source','evaluate'],['evaluate','objective']],variables:[{id:'E',name:'E',unit:'MPa',lo:600,hi:1600}],objectives:[{id:'rmse',name:'곡선 RMSE',direction:'min'}],constraints:[{id:'budget',name:'최대 비용',limit:100}],candidates:[{id:'c-01',E:720,rmse:.19,cost:40,actual:false},{id:'c-02',E:930,rmse:.12,cost:57,actual:false},{id:'c-03',E:1180,rmse:.08,cost:82,actual:false},{id:'c-04',E:1460,rmse:.15,cost:73,actual:false}],selectedCandidate:'c-03',budget:16,sourceId:'',sourceRevision:0,method:'DOE'};
    if(kind==='expert') return {...base, messages:[{id:'m-1',role:'demo-user',who:'예시 사용자 · 시연',text:'시험 곡선과 모델 차이가 커지는 원인을 어떻게 구분할까요?',replyTo:null,sources:[]},{id:'m-2',role:'moderator',who:'진행자 · 시연',text:'시험 조건, 경계조건, 재료 거동을 각각 검토하겠습니다. 먼저 누락된 관측을 알려주세요.',replyTo:'m-1',sources:[]}],issues:[{id:'issue-1',name:'동적 피크 차이',status:'미해결',messageIds:['m-1','m-2']}],evidence:[],selectedMessage:'m-2',paused:false,participants:['재료','시험','해석'],draft:'',demoReplyCount:0};
    return {...base, nodes:[],links:[],selectedNode:'',position:{}};
  }
  function createDoc() {modal(`<h2>새 ${esc(META[APP].name)} 문서</h2><label>문서 이름<input id="new-title" maxlength="120" value="${esc(META[APP].name+' 연구')}" autofocus></label><div class="dialog-actions">${btn('취소','dismiss')}${btn('파일 만들기','confirm-new','class="primary"')}</div>`);el('new-title').focus();el('new-title').select();}
  async function confirmNew() {
    const title=el('new-title')?.value.trim();if(!title){notify('문서 이름을 입력하세요.','bad');return;}
    if(s.dirty){s.live.pendingNewTitle=title;modal(`<h2>저장하지 않은 변경</h2><p>현재 문서의 변경을 처리한 뒤 새 문서를 만들 수 있습니다.</p><div class="dialog-actions">${btn('계속 편집','dismiss')}${btn('변경 버리고 새로 만들기','discard-new')}${btn('저장 후 새로 만들기','save-new','class="primary"')}</div>`);return;}
    await createDocNamed(title);
  }
  async function createDocNamed(title) {
    try { const doc=await api('/api/docs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:APP,title,data:initial(APP)})}); dismiss();openDocObject(doc); await loadList(); notify('새 파일을 디스크에 만들었습니다 · revision 1'); }
    catch(error) { failure(error); }
  }
  async function openDoc(docId, revision) {
    if (s.dirty) {s.live.pendingOpen={docId,revision};modal(`<h2>저장하지 않은 변경</h2><p>현재 문서의 변경을 처리한 뒤 다른 파일을 엽니다.</p><div class="dialog-actions">${btn('계속 편집','dismiss')}${btn('변경 버리고 열기','discard-open')}${btn('저장 후 열기','save-open','class="primary"')}</div>`);return;}
    try { const doc=await api('/api/docs/'+docId+(revision?'?revision='+encodeURIComponent(revision):'')); if(doc.kind!==APP) throw new Error('이 파일은 '+META[doc.kind]?.name+'에서 엽니다.'); openDocObject(doc); const latest=s.docs.find(x=>x.id===doc.id);s.readOnly=!!(latest&&latest.revision>doc.revision);if(s.readOnly)notify(`과거 revision ${doc.revision}을 읽기 전용으로 열었습니다. 최신은 r${latest.revision}입니다.`,'warn');render(); }
    catch(error) { failure(error); }
  }
  function openDocObject(doc) { if(doc.kind==='expert'&&doc.data?.messages?.[0]?.id==='m-1'&&doc.data.messages[0].who==='사용자'&&doc.data.messages[0].text==='시험 곡선과 모델 차이가 커지는 원인을 어떻게 구분할까요?'){doc.data.messages[0].who='예시 사용자 · 시연';doc.data.messages[0].role='demo-user';}s.doc=doc; s.selection=doc.data?.views?.selection||''; s.view=''; s.dirty=false; s.readOnly=false; s.undo=[]; s.live={}; if(!s.openIds.includes(doc.id)) s.openIds.push(doc.id); history.replaceState(null,'',location.pathname+'?id='+doc.id+'&revision='+doc.revision); render(); }
  async function saveDoc() {
    if (!s.doc) return;
    if(s.readOnly){notify('과거 revision은 읽기 전용입니다. 최신 파일을 열어 편집하세요.','warn');return;}
    const errors=validate(s.doc);
    if(errors.length) { notify(errors[0], 'bad'); return; }
    try {
      const doc=await api('/api/docs/'+s.doc.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedRevision:s.doc.revision,title:s.doc.title,data:s.doc.data})});
      s.doc=doc; s.dirty=false; s.undo=[]; history.replaceState(null,'',location.pathname+'?id='+doc.id+'&revision='+doc.revision); await loadList(); notify('디스크 저장 완료 · revision '+doc.revision);
    } catch(error) {
      if(error.status===409) showConflict(error.value.current);
      else failure(error);
    }
  }
  function showConflict(current) {
    s.live.conflict=current;
    modal(`<h2>외부 변경 충돌</h2>${note('같은 파일의 저장된 revision '+current.revision+'이 현재 편집본보다 새롭습니다. 저장을 중단했습니다.','warn')}<div class="row">현재 편집본 revision ${s.doc.revision} · 디스크 revision ${current.revision}</div><div class="dialog-actions">${btn('편집 계속','dismiss')}${btn('디스크 버전 다시 열기','reload-conflict')}</div>`);
  }
  function reallyClose(){if(s.doc)s.openIds=s.openIds.filter(x=>x!==s.doc.id);s.doc=null;s.selection='';s.view='';s.dirty=false;s.readOnly=false;s.undo=[];history.replaceState(null,'',location.pathname);render();}
  function closeDoc() {if(!s.dirty)return reallyClose();modal(`<h2>저장하지 않은 변경</h2><p>문서 변경을 저장하고 닫을지 선택하세요.</p><div class="dialog-actions">${btn('계속 편집','dismiss')}${btn('변경 버리고 닫기','discard-close')}${btn('저장 후 닫기','save-close','class="primary"')}</div>`);}
  function mutate(fn,message) { if(!s.doc) return;if(s.readOnly){notify('과거 revision은 읽기 전용입니다.','warn');return;}s.undo.push(clone(s.doc.data)); if(s.undo.length>40) s.undo.shift(); fn(s.doc.data); s.dirty=true; render(); if(message) notify(message); }
  function undo() { if(!s.undo.length||!s.doc)return; s.doc.data=s.undo.pop();s.dirty=true;render();notify('마지막 편집을 취소했습니다.'); }
  function validate(doc) {
    const d=doc.data,errors=[];
    if(doc.kind==='pre') { if(d.points.some(p=>!Number.isFinite(Number(p[0]))||!Number.isFinite(Number(p[1]))))errors.push('곡선에 숫자가 아닌 점이 있습니다.');for(let i=1;i<d.points.length;i++)if(Number(d.points[i][0])<Number(d.points[i-1][0]))errors.push(`점 ${i+1}의 X가 이전 점보다 작습니다.`); for(const seg of d.intervals){if(!Number.isFinite(Number(seg.start))||!Number.isFinite(Number(seg.end))||Number(seg.start)>=Number(seg.end)) errors.push(seg.name+'의 시작이 끝보다 작아야 합니다.');if(!Number.isFinite(Number(seg.weight))||Number(seg.weight)<0)errors.push(seg.name+'의 가중치가 잘못됐습니다.');}if(!Number.isFinite(Number(d.material.E))||Number(d.material.E)<=0)errors.push('재료 E는 0보다 커야 합니다.');if(!Number.isFinite(Number(d.material.nu))||Number(d.material.nu)<=-1||Number(d.material.nu)>=.5)errors.push('재료 ν 범위는 -1 초과, 0.5 미만입니다.');for(const c of d.conditions){if(!d.intervals.some(x=>x.id===c.target))errors.push(c.name+'의 대상 구간이 없습니다.');if(!Number.isFinite(Number(c.value))||!c.unit)errors.push(c.name+'의 값 또는 단위가 잘못됐습니다.');}if(!d.unitX||!d.unitY)errors.push('곡선 축 단위가 필요합니다.'); }
    if(doc.kind==='opt') { for(const v of d.variables) if(Number(v.lo)>=Number(v.hi)) errors.push(v.name+'의 하한이 상한보다 작아야 합니다.'); if(Number(d.budget)<1)errors.push('평가 예산은 1 이상이어야 합니다.'); }
    if(doc.kind==='post'&&Number(d.legendMin)>=Number(d.legendMax))errors.push('범례 최소값은 최대값보다 작아야 합니다.');
    return errors;
  }
  function getPath(obj,path) { return path.split('.').reduce((v,k)=>v?.[k],obj); }
  function setPath(obj,path,value) { const keys=path.split('.');let cur=obj;for(const key of keys.slice(0,-1))cur=cur[key];cur[keys.at(-1)]=value; }
  function fieldChange(target) { if(!s.doc)return;const path=target.dataset.field;if(!path)return;let value=target.type==='number'?Number(target.value):target.type==='checkbox'?target.checked:target.value;mutate(d=>setPath(d,path,value), '속성을 수정했습니다. 저장하면 새 revision이 됩니다.'); }
  function fieldInput(target) {if(!s.doc||s.readOnly)return;const path=target.dataset.field;if(!path)return;const value=target.type==='number'?(target.value===''?NaN:Number(target.value)):target.value;setPath(s.doc.data,path,value);s.dirty=true;el('document-title').textContent=s.doc.title+' ●';renderStatus();}
  function refreshEditedView(){if(!s.doc)return;el('tree').innerHTML=domainTree();el('stage-head').innerHTML=domainHead();const oldCanvas=el('stage-content').querySelector('.canvas-body');if(oldCanvas){const temporary=document.createElement('div');temporary.innerHTML=domainStage();const updated=temporary.querySelector('.canvas-body');if(updated)oldCanvas.innerHTML=updated.innerHTML;}renderDock();renderStatus();}
  function modal(html) { el('dialog-content').innerHTML=html; if(!el('dialog').open)el('dialog').showModal(); }
  function dismiss() { if(el('dialog').open)el('dialog').close(); }
  function renderStatus() { el('status-left').textContent=s.issue==='bad'?'● 오류 · '+s.notice:s.issue==='warn'?'● 주의 · '+s.notice:s.notice||'준비됨'; el('status-right').textContent=s.doc?`${s.doc.id.slice(0,8)} · r${s.doc.revision}${s.readOnly?' · 읽기 전용':''}${s.dirty?' · 저장 안 됨':''} · 서버 파일 저장`:'독립 실행 · 서버 파일 저장'; }
  function renderDock() { const errors=s.doc?validate(s.doc):[];el('dock-content').innerHTML=(errors.length?errors.map(x=>`<div class="dock-line bad">✕ ${esc(x)}</div>`).join(''):s.notice?`<div class="dock-line ${s.issue}">${esc(s.notice)}</div>`:'<div class="dock-line">선택한 대상의 진단과 작업 기록이 여기에 표시됩니다.</div>')+domainDock(); }
  function render() {
    el('app-name').textContent=META[APP].name;document.title=META[APP].name+' · CAE Design Lab';
    el('document-title').textContent=s.doc?s.doc.title+(s.dirty?' ●':''):'문서 없음';
    renderMenus();renderToolbar();renderTabs();renderStatus();renderDock();
    if(!s.doc){el('tree').innerHTML='';el('inspector').innerHTML='';el('stage-head').innerHTML='<div><h2>시작</h2><p>이 프로그램만 직접 시작해 파일을 열고 저장할 수 있습니다.</p></div>';renderLauncher();return;}
    el('tree').innerHTML=domainTree();el('stage-head').innerHTML=domainHead();el('stage-content').innerHTML=domainStage();el('inspector').innerHTML=domainInspector();
  }
  function renderMenus() {el('menubar').innerHTML=['파일','편집','선택','보기','도구','도움말'].map(x=>`<button data-menu="${x}">${x}</button>`).join('');}
  function renderToolbar() {el('toolbar').innerHTML=`${btn('＋ 새 문서','new')}${btn('⌕ 열기','open')}${btn('▣ 저장','save',s.doc&&!s.readOnly?'':'disabled')}${btn('↶ 취소','undo',s.undo.length?'':'disabled')}<span class="sep"></span>${s.doc?domainTools():`<span class="muted">${META[APP].sub} · 파일을 열거나 새 문서를 만드세요.</span>`}`;}
  function renderTabs() {el('tabs').innerHTML=s.openIds.map(docId=>{const doc=s.docs.find(x=>x.id===docId);return `<button data-open="${docId}" class="${s.doc?.id===docId?'active':''}">${esc(doc?.title||docId.slice(0,8))}${s.doc?.id===docId&&s.dirty?' ●':''}</button>`}).join('')+(s.doc?`<button data-act="close">× 닫기</button>`:'');}
  function renderLauncher() { const docs=s.docs.filter(x=>x.kind===APP); el('stage-content').innerHTML=`<div class="launcher"><div class="overline">LOCAL DESIGN LAB / ${esc(META[APP].sub)}</div><h1>${esc(META[APP].name)}</h1><p class="launcher-intro">각 프로그램의 문서는 독립 JSON 파일로 서버에 저장됩니다. 이 화면은 제품 설계 시안입니다.</p><div class="row">${btn('새 문서','new','class="primary"')}${btn('목록 새로고침','refresh')}</div><h3 style="margin-top:25px">최근 파일</h3>${docs.length?`<div class="recent">${docs.map(d=>`<button data-open="${d.id}"><strong>${esc(d.title)}</strong><small>r${d.revision} · ${esc(d.updatedAt||'')} · ${d.id.slice(0,8)}</small></button>`).join('')}</div>`:'<div class="empty">저장된 파일이 없습니다. 새 문서를 만들면 서버 디스크에 즉시 생성됩니다.</div>'}<div class="divider"></div><small>다른 도구에서 받은 링크의 객체 ID와 revision은 주소에서 검사합니다.</small></div>`; }

  const gb = {
    pre:['CSV 가져오기','csv-import','구간 추가','add-interval','검증','validate','케이스 전달','send-runner'],
    runner:['케이스 연결','link-case','실행 제출','run','선택 실행 중단','cancel-run','후처리 열기','send-post'],
    post:['ASCII/CSV 가져오기','csv-import','비교','compare','추출 CSV','export-csv'],
    opt:['평가기 연결','link-case','변수 추가','add-variable','시연 DOE','doe','후보 결과 열기','send-post'],
    expert:['자료 연결','link-evidence','일시중지/재개','pause','시연 응답','demo-reply','논점 추가','add-issue'],
    workbench:['객체 등록','register','연결 추가','connect','영향 확인','impact']
  };
  function domainTools() {const arr=gb[APP];return arr.filter((_,i)=>i%2===0).map((label,i)=>btn(label,arr[2*i+1])).join('');}
  function menuItems(name){if(name==='파일')return [['새 문서','new'],['열기','open'],['저장','save'],['JSON 내보내기','export-json'],['닫기','close']];if(name==='편집')return [['되돌리기','undo'],['이름 변경','rename']];if(name==='보기')return [['객체 패널','toggle-tree'],['속성 패널','toggle-inspector'],['진단 패널','toggle-dock']];if(name==='도구')return gb[APP].filter((_,i)=>i%2===0).map((x,i)=>[x,gb[APP][2*i+1]]);if(name==='도움말')return [['이 시안의 한계','about']];return [['선택 해제','clear-selection']];}
  function popMenu(name,anchor) {document.querySelector('.menu-pop')?.remove();const box=document.createElement('div');box.className='menu-pop';box.innerHTML=menuItems(name).map(([label,act])=>`<button data-act="${act}">${label}</button>`).join('');const rect=anchor.getBoundingClientRect();box.style.left=rect.left+'px';box.style.top=rect.bottom+'px';document.body.appendChild(box);}

  // Domain-specific renderers are below. The same persisted object powers tree, canvas and inspector.
  function domainTree(){return ({pre:preTree,runner:runnerTree,post:postTree,opt:optTree,expert:expertTree,workbench:wbTree})[APP]();}
  function domainHead(){return ({pre:preHead,runner:runnerHead,post:postHead,opt:optHead,expert:expertHead,workbench:wbHead})[APP]();}
  function domainStage(){return ({pre:preStage,runner:runnerStage,post:postStage,opt:optStage,expert:expertStage,workbench:wbStage})[APP]();}
  function domainInspector(){return ({pre:preInspector,runner:runnerInspector,post:postInspector,opt:optInspector,expert:expertInspector,workbench:wbInspector})[APP]();}
  function domainDock(){return ({pre:preDock,runner:runnerDock,post:postDock,opt:optDock,expert:expertDock,workbench:wbDock})[APP]();}

  function chart(points, options={}) {
    const W=700,H=310,L=54,R=22,T=22,B=43;
    if(!points?.length)return '<div class="empty">표시할 점이 없습니다. CSV를 가져오거나 점을 추가하세요.</div>';
    const finite=points.map(p=>[Number(p[0]),Number(p[1])]).filter(p=>p.every(Number.isFinite));
    if(!finite.length)return '<div class="empty">유효한 숫자 점이 없습니다.</div>';
    let xs=finite.map(p=>p[0]),ys=finite.map(p=>p[1]);
    if(options.overlay)for(const p of options.overlay){xs.push(Number(p[0]));ys.push(Number(p[1]));}
    let minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(0,...ys),maxY=Math.max(...ys);
    if(minX===maxX)maxX=minX+1;if(minY===maxY)maxY=minY+1;
    const x=v=>L+(Number(v)-minX)/(maxX-minX)*(W-L-R),y=v=>H-B-(Number(v)-minY)/(maxY-minY)*(H-T-B);
    const line=arr=>arr.map((p,i)=>`${i?'L':'M'}${x(p[0]).toFixed(1)},${y(p[1]).toFixed(1)}`).join(' ');
    let marks='';for(let i=0;i<5;i++){let xx=L+i*(W-L-R)/4,yy=T+i*(H-T-B)/4;marks+=`<line class="gridline" x1="${xx}" y1="${T}" x2="${xx}" y2="${H-B}"/><line class="gridline" x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}"/><text x="${xx}" y="${H-18}" fill="#91a9b4" text-anchor="middle" font-size="11">${fmt(minX+i*(maxX-minX)/4)}</text><text x="${L-8}" y="${yy+4}" fill="#91a9b4" text-anchor="end" font-size="11">${fmt(maxY-i*(maxY-minY)/4)}</text>`;}
    let ranges='';for(const seg of options.intervals||[]){const left=x(seg.start),right=x(seg.end);const condition=s.selection.startsWith('cond:')&&s.doc?.data?.conditions?.find(c=>c.id===s.selection.slice(5));const active=s.selection==='interval:'+seg.id||condition?.target===seg.id;ranges+=`<rect class="range ${active?'active':''}" data-select="interval:${esc(seg.id)}" x="${Math.min(left,right)}" y="${T}" width="${Math.max(3,Math.abs(right-left))}" height="${H-T-B}"/>`;}
    const pointsSvg=points.map((p,i)=>`<circle class="point ${s.selection==='point:'+i?'active':''}" data-select="point:${i}" cx="${x(p[0])}" cy="${y(p[1])}" r="4.5"><title>점 ${i+1}: ${fmt(p[0])}, ${fmt(p[1])}</title></circle>`).join('');
    return `<svg class="plot" viewBox="0 0 ${W} ${H}" role="img" aria-label="편집 가능한 곡선"><rect x="0" y="0" width="${W}" height="${H}" fill="#14242d"/>${marks}${ranges}<path class="series" d="${line(points)}"/>${options.overlay?`<path class="series alt" d="${line(options.overlay)}"/>`:''}${pointsSvg}<text x="${W/2}" y="${H-4}" fill="#a9bbc4" text-anchor="middle" font-size="11">${esc(options.xLabel||'시간')}</text><text x="15" y="${H/2}" fill="#a9bbc4" transform="rotate(-90 15 ${H/2})" text-anchor="middle" font-size="11">${esc(options.yLabel||'응답')}</text></svg>`;
  }
  function docHeader(title,sub,actions='') {return `<div><div class="overline">${META[APP].name} / ${esc(sub)}</div><h2>${esc(title)}</h2></div><span class="spacer"></span>${actions}`;}
  function propGroup(title,html) {return `<section class="property-group"><h3>${esc(title)}</h3><div class="body">${html}</div></section>`;}

  // Preprocessor: the selected curve point, interval or imported mesh face has one ID across all panes.
  function preTree(){const d=s.doc.data;return group('작업 대상')+tree('시험 데이터 · '+d.points.length+'점','curve','⌁',d.points.length)+d.points.map((p,i)=>tree(`점 ${i+1} · ${fmt(p[0])}, ${fmt(p[1])}`,'point:'+i,'·')).join('')+group('구간')+d.intervals.map(x=>tree(x.name,'interval:'+x.id,'▤')).join('')+group('모델과 조건')+tree(d.material.name,'material','▣')+d.conditions.map(x=>tree(x.name,'cond:'+x.id,'⛶')).join('')+(d.mesh.length?group('가져온 메시')+tree('OBJ · '+d.mesh.length+'개 면','mesh','⬡')+d.mesh.map((_,i)=>tree('면 '+(i+1),'face:'+i,'△')).join(''):'');}
  function preHead(){const d=s.doc.data;return docHeader(d.mode==='mesh'?'메시·영역 편집':'실험 곡선과 구간','대상 편집',`${pill(d.source)} ${pill(s.dirty?'저장 안 됨':'저장됨',s.dirty?'warn':'good')}`);}
  function meshSvg(d){const verts=d.vertices||[];const faces=d.mesh||[];if(!faces.length)return '<div class="empty">OBJ의 삼각형 면이 없습니다.</div>';const px=v=>80+Number(v[0])*420,py=v=>300-Number(v[1])*220;return `<svg class="plot" viewBox="0 0 650 350" aria-label="가져온 OBJ 면 선택"><rect width="650" height="350" fill="#12212a"/>${faces.map((face,i)=>{const coords=face.map(k=>verts[k]).filter(Boolean);if(coords.length<3)return '';return `<polygon data-select="face:${i}" class="field-cell ${s.selection==='face:'+i?'active':''}" points="${coords.map(v=>`${px(v)},${py(v)}`).join(' ')}" fill="${i%2?'#398878':'#326c82'}"><title>원본 OBJ 면 ${i+1}</title></polygon>`}).join('')}</svg>`;}
  function preStage(){const d=s.doc.data;return `<div class="stack"><div class="row">${btn('곡선','view-curve',`class="${d.mode==='curve'?'selected':''}"`)}${btn('메시','view-mesh',`class="${d.mode==='mesh'?'selected':''}" ${d.mesh.length?'':'disabled'}`)}<span class="spacer"></span>${btn('점 추가','add-point')}${btn('OBJ 메시 가져오기','obj-import')}</div>${d.mode==='mesh'?`<div class="canvas-frame"><div class="canvas-toolbar"><b>${esc(d.meshName||'OBJ 메시')}</b>${pill(d.mesh.length+'면')}</div><div class="canvas-body">${meshSvg(d)}</div><div class="canvas-note">실제 OBJ 좌표에서 투영 · 면 ID 선택 시 트리와 속성이 연동됩니다.</div></div>`:`<div class="canvas-frame"><div class="canvas-toolbar"><b>${esc(d.source)}</b><span class="muted">X ${esc(d.unitX)} · Y ${esc(d.unitY)}</span><span class="spacer"></span>${pill(d.intervals.length+' 구간')}</div><div class="canvas-body">${chart(d.points,{intervals:d.intervals,xLabel:'시간 ['+d.unitX+']',yLabel:'응답 ['+d.unitY+']'})}</div><div class="canvas-note">점과 음영 구간을 클릭하세요. 트리 선택과 같은 객체입니다.</div></div>`}<div class="row">${btn('조건 추가','add-condition')}${btn('선택 삭제','delete-selected')}${btn('입력 검증','validate')}</div></div>`;}
  function preInspector(){const d=s.doc.data,key=s.selection;if(key.startsWith('point:')){const i=Number(key.split(':')[1]),p=d.points[i];if(!p)return '';return `<div class="inspector-title">곡선 점 ${i+1}</div>${propGroup('좌표와 단위',field('X ['+d.unitX+']','points.'+i+'.0',p[0],'number','step="any"')+field('Y ['+d.unitY+']','points.'+i+'.1',p[1],'number','step="any"'))}${propGroup('대상',row('ID','point:'+i)+row('출처',d.source))}`;}
    if(key.startsWith('interval:')){const i=d.intervals.findIndex(x=>x.id===key.split(':')[1]),a=d.intervals[i];if(!a)return '';return `<div class="inspector-title">${esc(a.name)}</div>${propGroup('구간',field('이름','intervals.'+i+'.name',a.name)+field('시작 ['+d.unitX+']','intervals.'+i+'.start',a.start,'number','step="any"')+field('끝 ['+d.unitX+']','intervals.'+i+'.end',a.end,'number','step="any"')+field('가중치','intervals.'+i+'.weight',a.weight,'number','min="0" step="any"'))}${propGroup('연결',row('조건',d.conditions.filter(c=>c.target===a.id).map(c=>c.name).join(', ')||'없음'))}`;}
    if(key==='material')return `<div class="inspector-title">${esc(d.material.name)}</div>${propGroup('재료',field('이름','material.name',d.material.name)+select('법칙','material.law',d.material.law,['선형 탄성','Neo-Hooke','실험 기반'])+field('E [MPa]','material.E',d.material.E,'number','step="any" min="0"')+field('ν','material.nu',d.material.nu,'number','step="any" min="0" max="0.5"'))}${note('저장한 Case revision을 실행기가 고정 참조합니다.')}`;
    if(key.startsWith('cond:')){const i=d.conditions.findIndex(x=>x.id===key.split(':')[1]),c=d.conditions[i];if(!c)return '';const targets=`<label>대상 구간<select data-field="conditions.${i}.target">${d.intervals.map(x=>`<option value="${esc(x.id)}" ${x.id===c.target?'selected':''}>${esc(x.name)} · ${esc(x.id)}</option>`).join('')}</select></label>`;return `<div class="inspector-title">${esc(c.name)}</div>${propGroup('조건',field('이름','conditions.'+i+'.name',c.name)+targets+field('값','conditions.'+i+'.value',c.value,'number','step="any"')+field('단위','conditions.'+i+'.unit',c.unit))}${row('ID',c.id)}`;}
    if(key.startsWith('face:')){const i=Number(key.split(':')[1]);return `<div class="inspector-title">OBJ 면 ${i+1}</div>${propGroup('영역',row('원본 면 ID',i+1)+row('절점 인덱스',d.mesh[i]?.map(v=>v+1).join(', ')))+note('이 OBJ 시안은 면 선택과 저장을 확인합니다. 조건의 실제 solver 매핑은 후속 제품 연결 항목입니다.','warn')}`;}
    return `<div class="inspector-title">데이터셋</div>${propGroup('표시',row('점',d.points.length)+row('구간',d.intervals.length)+field('X 단위','unitX',d.unitX)+field('Y 단위','unitY',d.unitY))}${note('중앙의 점/구간 또는 트리 항목을 선택하면 이 속성이 바뀝니다.')}`;
  }
  function preDock(){if(!s.doc||APP!=='pre')return '';const d=s.doc.data;return `<div class="dock-line">소스: ${esc(d.source)} · ${d.points.length}개 점 · ${d.intervals.length}개 구간 · ${d.mesh.length}개 메시 면</div><div class="dock-line">검증: ${validate(s.doc).length?'수정 필요':'기본 값 범위 통과'} · 실제 물리 검증은 수행하지 않음</div>`;}

  // Runner: each run freezes its input revision and keeps old results after case edits.
  function selectedRun(){const d=s.doc.data;const rid=s.selection.startsWith('run:')?s.selection.slice(4):d.selectedRun;return d.runs.find(r=>r.id===rid)||d.runs.at(-1);}
  function runnerTree(){const d=s.doc.data;return group('케이스')+d.cases.map(c=>tree(c.name,'case:'+c.id,'▣',c.sourceRevision?'r'+c.sourceRevision:'독립')).join('')+group('실행 큐 / 이력')+d.runs.map(r=>tree(r.name,'run:'+r.id,r.status==='done'?'●':r.status==='cancelled'?'×':'▷',r.status==='done'?'완료':r.status)).join('');}
  function runnerHead(){const r=selectedRun();return docHeader(r?r.name:'케이스와 실행 큐','실행 관리',r?`${pill(r.status,r.status==='done'?'good':r.status==='cancelled'?'warn':'')} ${pill('입력 r'+r.inputRevision)}`:pill('실행 기록 없음'));}
  function runnerStage(){const d=s.doc.data,r=selectedRun();return `<div class="stack">${note('시연 실행: 이 시안은 실제 solver를 호출하지 않습니다. 입력 revision, 상태, 로그, 수렴 곡선의 화면 계약만 검증합니다.','warn')}<div class="row">${btn('입력 검증','validate-case')}${btn('새 시연 실행','run','class="primary"')}${r?btn('선택 재실행','retry-run'):''}${r&&['queued','running'].includes(r.status)?btn('중단','cancel-run'):''}</div><div class="workspace-split"><div class="canvas-frame"><div class="canvas-toolbar"><b>${r?'실행 '+esc(r.id):'실행을 선택하세요'}</b><span class="spacer"></span>${r?pill(r.status,r.status==='done'?'good':r.status==='cancelled'?'warn':''):''}</div><div class="canvas-body">${r?`${chart(r.convergence||[],{xLabel:'반복',yLabel:'잔차'})}<div class="row">${pill('입력 스냅샷 r'+r.inputRevision)}${pill('백엔드: '+r.backend)}</div>`:'<div class="empty">왼쪽에서 실행 이력을 선택하거나 새 실행을 제출하세요.</div>'}</div></div><div class="side-rail"><h3>큐와 상태</h3>${d.runs.length?d.runs.map(x=>`<button class="list-button ${r?.id===x.id?'selected':''}" data-select="run:${x.id}">${esc(x.name)}<br><small>${esc(x.status)} · 입력 r${x.inputRevision}</small></button>`).join(''):'<small>실행 없음</small>'}</div></div><section class="property-group"><h3>로그 · 선택 실행</h3><div class="body mono">${r?(r.log||[]).map(line=>`<div class="dock-line">${esc(line)}</div>`).join(''):'기록 없음'}</div></section></div>`;}
  function runnerInspector(){const d=s.doc.data,key=s.selection;if(key.startsWith('case:')){const i=d.cases.findIndex(x=>x.id===key.slice(5)),c=d.cases[i];if(!c)return '';return `<div class="inspector-title">${esc(c.name)}</div>${propGroup('케이스',field('이름','cases.'+i+'.name',c.name)+select('백엔드','cases.'+i+'.backend',c.backend,['시연 계산기','기존 Python 엔진 연결 예정','외부 등록 실행기 연결 예정'])+row('입력 객체',c.sourceId||'독립 예시')+row('고정 revision',c.sourceRevision||'없음'))}${note('실제 backend 사용 가능 여부는 본 제품 서비스에서 검사합니다.','warn')}`;}
    const r=selectedRun();if(!r)return `${propGroup('설정',field('CPU 스레드','resources.threads',d.resources.threads,'number','min="1"'))}${note('전처리 파일을 연결하거나 독립 케이스를 실행할 수 있습니다.')}`;
    return `<div class="inspector-title">${esc(r.name)}</div>${propGroup('입력 고정',row('Run ID',r.id)+row('Case ID',r.caseId)+row('입력 revision',r.inputRevision)+row('Backend',r.backend))}${propGroup('실행 상태',row('상태',r.status)+row('시작',r.startedAt||'—')+row('결과',r.resultId||'없음')+row('종료 원인',r.reason||'—'))}${r.status==='done'?btn('후처리에서 결과 열기','send-post','class="primary"'):''}`;}
  function runnerDock(){if(!s.doc||APP!=='runner')return '';const r=selectedRun();return r?`<div class="dock-line">${esc(r.name)} · ${esc(r.status)} · 원본 입력 r${r.inputRevision} 고정</div><div class="dock-line">${esc(r.log?.at(-1)||'대기 중')}</div>`:'<div class="dock-line">케이스를 선택해 입력을 점검하고 실행하세요.</div>';}

  // Postprocessor: field frame/location and imported ASCII curves use the same saved dataset selection.
  function currentDataset(){const d=s.doc.data;return d.datasets.find(x=>x.id===d.selectedDataset)||d.datasets[0];}
  function postTree(){const d=s.doc.data;return group('결과 데이터')+d.datasets.map(x=>tree(x.name,'dataset:'+x.id,x.kind==='field'?'▦':'⌁',x.kind)).join('')+group('선택·비교')+tree('프레임 '+d.frame,'frame','◷')+tree('위치 '+(d.location+1),'cell:'+d.location,'⊙')+(d.compareId?tree('비교 · '+d.compareId,'compare','⇄'):'');}
  function postHead(){const r=currentDataset();return docHeader(r?.name||'결과 없음','결과 탐색',`${r?pill(r.kind==='field'?'필드':'곡선'):''} ${pill('원본: '+(r?.source||'없음'))}`);}
  function fieldValues(r,d){const values=r.values?.[Math.min(Number(d.frame),r.values.length-1)]||[];return d.component==='σyy'&&r.source==='시안 내장'?values.map(v=>Number((v*.68).toFixed(3))):values;}
  function fieldView(r,d){const values=fieldValues(r,d);const min=Number(d.legendMin),max=Number(d.legendMax);const colors=v=>{const t=Math.min(1,Math.max(0,(v-min)/(max-min||1)));const hue=225-205*t;return `hsl(${hue} 70% ${38+12*t}%)`};return `<svg class="plot" viewBox="0 0 700 310" role="img" aria-label="필드 셀 ID 선택"><rect width="700" height="310" fill="#13232d"/>${values.map((v,i)=>{const x=95+(i%4)*122,y=29+Math.floor(i/4)*82;return `<rect data-select="cell:${i}" class="field-cell ${s.selection==='cell:'+i?'active':''}" x="${x}" y="${y}" width="117" height="77" rx="2" fill="${colors(Number(v))}"><title>위치 ${i+1}, ${fmt(v)} ${esc(r.unit)}</title></rect><text x="${x+57}" y="${y+43}" text-anchor="middle" fill="#fff" font-size="13" pointer-events="none">${fmt(v)}</text>`}).join('')}<text x="600" y="41" fill="#aac1ca" font-size="11">${esc(d.component)} · t=${d.frame} · 시연 필드</text></svg>`;}
  function postStage(){const d=s.doc.data,r=currentDataset(),compare=d.datasets.find(x=>x.id===d.compareId);return `<div class="stack"><div class="row">${r&&r.kind==='field'?`${select('성분 · 시연 필드','component',d.component,['σxx','σyy'])}${field('프레임','frame',d.frame,'number',`min="0" max="${r.frames.length-1}" step="1"`)}`:''}${btn('ASCII/CSV 가져오기','csv-import')}${btn('추출 CSV','export-csv')}</div>${r?`<div class="canvas-frame"><div class="canvas-toolbar"><b>${esc(r.name)}</b><span class="spacer"></span>${pill(r.unit)} ${pill(r.kind)}</div><div class="canvas-body">${r.kind==='field'?fieldView(r,d):chart(r.curve||[],{overlay:compare?.curve,xLabel:r.axisName||'시간',yLabel:r.name+' ['+r.unit+']'})}<div class="legend"><span class="legend-swatch"></span>${esc(r.name)} · ${esc(r.unit)}${compare?`<span style="color:#e8bc79">■ ${esc(compare.name)}</span>`:''}</div></div><div class="canvas-note">${r.kind==='field'?'셀을 선택하면 위치·값·범례가 연동됩니다.':'점 선택은 응답 위치 속성을 엽니다.'}</div></div>`:'<div class="empty">결과를 가져오세요.</div>'}<div class="row">${r?.kind==='field'?`${field('범례 최솟값','legendMin',d.legendMin,'number','step="any"')}${field('범례 최댓값','legendMax',d.legendMax,'number','step="any"')}`:''}<label>비교 결과<select data-field="compareId"><option value="">비교 없음</option>${d.datasets.filter(x=>x.id!==r?.id).map(x=>`<option value="${x.id}" ${x.id===d.compareId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label></div></div>`;}
  function postInspector(){const d=s.doc.data,r=currentDataset(),key=s.selection;if(key.startsWith('dataset:')){const x=d.datasets.find(v=>v.id===key.slice(8));if(x?.id!==d.selectedDataset){d.selectedDataset=x.id;return postInspector();}}
    if(key.startsWith('cell:')){const i=Number(key.slice(5)),val=fieldValues(r,d)[i];return `<div class="inspector-title">위치 ${i+1}</div>${propGroup('선택 결과',row('성분',d.component)+row('프레임',d.frame)+row('값',fmt(val)+' '+r.unit)+row('데이터셋',r.id))}${note('선택한 위치는 문서에 보존됩니다.')}`;}
    const curve=r?.kind==='curve',values=curve?(r.curve||[]).map(p=>Number(p[1])):[];const display=curve?row('채널',r.name)+row('축',r.axisName||'축 미정')+row('표본',r.curve?.length||0)+row('값 범위',values.length?fmt(Math.min(...values))+'…'+fmt(Math.max(...values))+' '+r.unit:'—'):row('프레임',d.frame)+row('성분',d.component)+row('범례',d.legendMin+'…'+d.legendMax);return `<div class="inspector-title">${esc(r?.name||'결과 없음')}</div>${propGroup('원본',row('형식',r?.kind||'—')+row('출처',r?.source||'—')+row('단위',r?.unit||'—')+row('원본 ID',r?.id||'—'))}${propGroup('현재 표시',display)}`;}
  function postDock(){if(!s.doc||APP!=='post')return '';const r=currentDataset();return `<div class="dock-line">${esc(r?.name||'없음')} · ${esc(r?.source||'')} · ${r?.kind==='field'?r.values?.length+' 프레임':r?.curve?.length+' 표본'}</div><div class="dock-line">ASCII 가져오기는 실제 로컬 파일에서 숫자 열을 읽고 이 JSON 문서에 보존합니다.</div>`;}

  // Study: procedure is a real selectable node graph; candidates are clearly marked as supplied examples or generated demonstration.
  function optTree(){const d=s.doc.data;return group('평가 절차')+d.nodes.map(n=>tree(n.type+' · '+n.id,'node:'+n.id,'⬡')).join('')+group('변수 · 목적 · 제약')+d.variables.map(v=>tree(v.name,'variable:'+v.id,'↔')).join('')+d.objectives.map(v=>tree(v.name,'objective:'+v.id,'◎')).join('')+d.constraints.map(v=>tree(v.name,'constraint:'+v.id,'⊣')).join('')+group('후보')+d.candidates.map(c=>tree(c.id,'candidate:'+c.id,'●',c.actual?'측정':'시연')).join('');}
  function optHead(){const d=s.doc.data;return docHeader('평가 절차와 설계 공간','연구 편집',`${pill(d.method)} ${pill(d.candidates.length+' 후보')} ${pill('평가 예산 '+d.budget)}`);}
  function optGraph(){const d=s.doc.data;const get=n=>d.nodes.find(v=>v.id===n);return `<div class="canvas-frame" style="height:265px;min-height:265px"><div class="canvas-toolbar"><b>평가 절차</b><span class="spacer"></span>${btn('단계 추가','add-node')}${btn('선택 단계 삭제','delete-selected')}</div><div style="position:relative;height:217px">${`<svg class="edge-layer" viewBox="0 0 700 217" preserveAspectRatio="none">${d.edges.map(([a,b])=>{const p=get(a),q=get(b);if(!p||!q)return '';const x1=(p.x/100*700)+115,y1=(p.y/100*217)+26,x2=q.x/100*700,y2=(q.y/100*217)+26;return `<path d="M${x1},${y1} C${x1+70},${y1} ${x2-70},${y2} ${x2},${y2}"/>`}).join('')}</svg>`}${d.nodes.map(n=>`<div class="node ${s.selection==='node:'+n.id?'active':''}" data-select="node:${n.id}" style="left:${n.x}%;top:${n.y}%;transform:translateY(-50%)"><b>${esc(n.type)}</b><div class="mono">${esc(n.id)}</div><div class="ports"><span><i class="dot"></i> 입력</span><span>출력 <i class="dot"></i></span></div></div>`).join('')}</div><div class="canvas-note">노드를 선택해 이름·위치를 편집하고 연결을 검토하세요.</div></div>`;}
  function optScatter(){const d=s.doc.data, cs=d.candidates;const x=c=>80+(Number(c.E)-500)/1200*520,y=c=>250-(Number(c.rmse)-.03)/.22*200;return `<svg class="plot" viewBox="0 0 700 295" aria-label="후보 설계 공간"><rect width="700" height="295" fill="#14242d"/>${[0,1,2,3,4].map(i=>`<line class="gridline" x1="${80+i*130}" y1="35" x2="${80+i*130}" y2="250"/><line class="gridline" x1="80" y1="${35+i*54}" x2="600" y2="${35+i*54}"/>`).join('')}${cs.map(c=>`<circle class="point ${s.selection==='candidate:'+c.id||d.selectedCandidate===c.id?'active':''}" data-select="candidate:${c.id}" cx="${x(c)}" cy="${y(c)}" r="${c.id===d.selectedCandidate?8:6}" fill="${c.actual?'#80c5a3':'#e5bb79'}"><title>${c.id}: E=${c.E}, RMSE=${c.rmse}</title></circle><text x="${x(c)+9}" y="${y(c)-5}" font-size="10" fill="#bbcad0">${esc(c.id)}</text>`).join('')}<text x="340" y="284" fill="#9fb7bf" text-anchor="middle">E [MPa]</text><text x="22" y="145" fill="#9fb7bf" transform="rotate(-90 22 145)" text-anchor="middle">곡선 RMSE</text></svg>`;}
  function optStage(){const d=s.doc.data,view=s.view||d.views.optView||'space',selected=d.candidates.find(x=>x.id===d.selectedCandidate)||d.candidates[0],other=d.candidates.find(x=>x.id!==selected?.id);const tabs=`<div class="row view-tabs">${btn('평가 절차','opt-view-workflow',`class="${view==='workflow'?'selected':''}"`)}${btn('설계 공간','opt-view-space',`class="${view==='space'?'selected':''}"`)}${btn('후보 비교','opt-view-compare',`class="${view==='compare'?'selected':''}"`)}</div>`;if(view==='workflow')return `<div class="stack">${tabs}${note('노드를 선택해 입출력 속성을 편집합니다. 이 절차의 실제 평가기는 아직 연결되지 않았습니다.','warn')}${optGraph()}<div class="row">${btn('변수 추가','add-variable')}${btn('평가기 연결','link-case')}${btn('예시 DOE 생성','doe')}</div></div>`;if(view==='compare')return `<div class="stack">${tabs}<div class="row"><b>선택 후보 ${esc(selected?.id||'없음')}</b><span class="spacer"></span><label>비교 후보<select data-field="compareCandidate"><option value="">자동 선택</option>${d.candidates.filter(x=>x.id!==selected?.id).map(x=>`<option value="${x.id}" ${d.compareCandidate===x.id?'selected':''}>${esc(x.id)}</option>`).join('')}</select></label></div><div class="grid2">${[selected,d.candidates.find(x=>x.id===d.compareCandidate)||other].map(c=>`<section class="property-group"><h3>${esc(c?.id||'없음')} ${c?pill(c.actual?'가져온 값':'시연 값',c.actual?'good':'warn'):''}</h3><div class="body">${c?row('E',fmt(c.E)+' MPa')+row('곡선 RMSE',fmt(c.rmse))+row('평가 비용',fmt(c.cost))+row('출처',c.source||'시연 예시'):'비교 후보를 선택하세요.'}</div></section>`).join('')}</div>${note('후보 값은 시안의 기록입니다. 실제 Run/Result와 비교하려면 각 후보의 원본 평가 참조가 필요합니다.','warn')}${btn('설계 공간으로','opt-view-space')}</div>`;return `<div class="stack">${tabs}<div class="row">${btn('예시 DOE 생성','doe')}${btn('후보 CSV 가져오기','candidate-import')}${pill('노랑 = 시연 값')}${pill('초록 = 가져온 값','good')}</div><div class="canvas-frame"><div class="canvas-toolbar"><b>설계 공간 · 후보 선택</b><span class="spacer"></span>${pill(d.candidates.length+' 후보')}</div><div class="canvas-body">${optScatter()}</div></div>${note('점 또는 왼쪽 후보 트리를 선택하면 이 설계 공간과 오른쪽 속성이 함께 갱신됩니다. 시작 후보는 시연 값입니다.','warn')}</div>`;}
  function optInspector(){const d=s.doc.data,key=s.selection;if(key.startsWith('node:')){const i=d.nodes.findIndex(n=>n.id===key.slice(5)),n=d.nodes[i];if(!n)return '';return `<div class="inspector-title">${esc(n.type)}</div>${propGroup('절차 노드',field('종류','nodes.'+i+'.type',n.type)+field('X 위치 [%]','nodes.'+i+'.x',n.x,'number','min="0" max="80"')+field('Y 위치 [%]','nodes.'+i+'.y',n.y,'number','min="0" max="90"')+row('포트','입력 → 출력'))}${propGroup('연결',d.edges.filter(e=>e.includes(n.id)).map(e=>row(e[0],e[1])).join('')||'연결 없음')}`;}
    if(key.startsWith('variable:')){const i=d.variables.findIndex(v=>v.id===key.slice(9)),v=d.variables[i];if(!v)return '';return `<div class="inspector-title">${esc(v.name)}</div>${propGroup('변수 범위',field('이름','variables.'+i+'.name',v.name)+field('단위','variables.'+i+'.unit',v.unit)+field('하한','variables.'+i+'.lo',v.lo,'number','step="any"')+field('상한','variables.'+i+'.hi',v.hi,'number','step="any"'))}`;}
    if(key.startsWith('candidate:')){const c=d.candidates.find(v=>v.id===key.slice(10));if(!c)return '';return `<div class="inspector-title">${esc(c.id)}</div>${propGroup('후보 상세',row('E',fmt(c.E)+' MPa')+row('RMSE',fmt(c.rmse))+row('비용',fmt(c.cost))+row('출처',c.actual?'가져온 실제 표본':'시연 값'))}${btn('이 후보를 전처리에서 열기','send-pre')}${btn('비교에 넣기','candidate-compare')}`;}
    return `<div class="inspector-title">연구 설정</div>${propGroup('실행',select('방법','method',d.method,['DOE','동정','최적화','UQ','민감도','대리모델'])+field('평가 예산','budget',d.budget,'number','min="1"')+row('입력 객체',d.sourceId||'없음')+row('고정 revision',d.sourceRevision||'—'))}${note('예산과 범위의 변경은 저장 시 새 Study revision입니다.')}`;}
  function optDock(){if(!s.doc||APP!=='opt')return '';const d=s.doc.data;return `<div class="dock-line">절차 ${d.nodes.length} 단계 · ${d.edges.length} 연결 · 변수 ${d.variables.length} · 후보 ${d.candidates.length}</div><div class="dock-line">후보의 실제성은 각 기록의 출처 속성에서 확인합니다.</div>`;}

  // Expert: persisted message timeline with reply-to and interruption. Demo replies never impersonate a live model.
  function expertTree(){const d=s.doc.data;return group('세션')+tree(s.doc.title,'session','◎')+group('논점')+d.issues.map(i=>tree(i.name,'issue:'+i.id,'◇',i.status)).join('')+group('근거')+d.evidence.map(e=>tree(e.name,'evidence:'+e.id,'▣')).join('')+group('대화')+d.messages.map(m=>tree(m.who+' · '+m.text.slice(0,17),'message:'+m.id,m.role==='user'?'●':m.role==='moderator'?'◆':'◇')).join('');}
  function expertHead(){const d=s.doc.data;return docHeader(s.doc.title,'대화와 논점',`${pill(d.paused?'일시중지':'진행 가능',d.paused?'warn':'good')} ${pill(d.messages.length+' 발언')}`);}
  function expertStage(){const d=s.doc.data,issue=s.selection.startsWith('issue:')?d.issues.find(x=>x.id===s.selection.slice(6)):null,selectedMessage=s.selection.startsWith('message:')?s.selection.slice(8):null;return `<div class="chat-layout"><div class="chat-main"><div class="timeline" id="timeline">${d.messages.map(m=>`<article class="message ${m.role} ${selectedMessage===m.id?'active':''} ${issue?.messageIds.includes(m.id)?'issue-linked':''}" data-select="message:${m.id}"><div class="meta"><b>${esc(m.who)}</b>${pill(m.role==='demo'?'시연 응답':m.role==='moderator'?'시연 진행자':m.role==='user'?'사용자 입력':m.role==='demo-user'?'시연 질문':m.role)}<span class="spacer"></span><span>${esc(m.id)}</span></div><p>${esc(m.text)}</p>${m.replyTo?`<div class="reply" data-select="message:${m.replyTo}">↳ ${esc(m.replyTo)}에 답변 · 원 발언 선택</div>`:''}${m.sources?.length?`<div class="reply">근거: ${m.sources.map(esc).join(', ')}</div>`:''}</article>`).join('')}</div><div class="composer"><textarea id="compose" aria-label="대화 입력" placeholder="추가 관측, 반론 또는 질문을 입력하세요. ${d.paused?'일시중지 중에도 기록할 수 있습니다.':''}"></textarea><div class="stack">${btn('보내기','send-message','class="primary"')}${btn('시연 응답','demo-reply')}</div></div></div><aside class="chat-side"><h3>논점 지도</h3><small>발언 선택 시 관련 논점이 강조됩니다.</small>${d.issues.map(i=>`<button class="topic ${s.selection==='issue:'+i.id||selectedMessage&&i.messageIds.includes(selectedMessage)?'selected':''}" data-select="issue:${i.id}">◇ ${esc(i.name)}<br><small>${esc(i.status)} · 발언 ${i.messageIds.length}</small></button>`).join('')}<div class="divider"></div><h3>진행</h3><p class="muted" style="font-size:11px;margin:7px 0">사용자 중간 개입은 선택한 발언에 답글로 기록됩니다. 모델을 호출하지 않습니다.</p>${btn(d.paused?'이어가기':'일시중지','pause')}</aside></div>`;}
  function expertInspector(){const d=s.doc.data,key=s.selection;if(key.startsWith('message:')){const m=d.messages.find(v=>v.id===key.slice(8));if(!m)return '';return `<div class="inspector-title">${esc(m.who)}</div>${propGroup('발언',row('ID',m.id)+row('유형',m.role)+row('답변 대상',m.replyTo||'원 질문')+row('근거',m.sources?.join(', ')||'없음'))}${m.replyTo?btn('원 발언으로 이동','jump-reply'):''}${btn('이 발언에 답하기','reply-to')}`;}
    if(key.startsWith('issue:')){const i=d.issues.find(v=>v.id===key.slice(6));if(!i)return '';return `<div class="inspector-title">${esc(i.name)}</div>${propGroup('논점',row('상태',i.status)+row('관련 발언',i.messageIds.join(', ')))+note('논점은 증거와 반론을 묶습니다. 전문가 합의가 인과 증명은 아닙니다.')}`;}
    if(key.startsWith('evidence:')){const e=d.evidence.find(v=>v.id===key.slice(9));return `<div class="inspector-title">${esc(e?.name||'근거')}</div>${propGroup('출처',row('문서 ID',e?.docId||'—')+row('고정 revision',e?.revision||'—'))}${e?.docId?btn('출처 열기','open-evidence'):''}`;}
    return `<div class="inspector-title">참여자와 범위</div>${propGroup('세션',row('참여 관점',d.participants.join(' · '))+row('상태',d.paused?'일시중지':'진행 가능')+row('실제 LLM','연결 안 됨'))}${note('시연 응답은 고정된 문구입니다. 실제 자료 전송이나 모델 호출은 없습니다.','warn')}`;}
  function expertDock(){if(!s.doc||APP!=='expert')return '';const d=s.doc.data;return `<div class="dock-line">메시지 ${d.messages.length} · 논점 ${d.issues.length} · 근거 ${d.evidence.length}</div><div class="dock-line">사용자 발언과 reply-to는 저장 후 다시 열어도 유지됩니다.</div>`;}

  // Workbench: external documents retain ownership. Links pin revisions and compute stale state from current files.
  function wbNode(key){return s.doc.data.nodes.find(x=>x.id===key);}
  function wbStale(link){const node=wbNode(link.from),upstream=s.docs.find(x=>x.id===node?.docId);return !upstream?'broken':link.fromHash&&upstream.semanticHash?upstream.semanticHash!==link.fromHash?'stale':'current':upstream.revision>link.fromRevision?'stale':'current';}
  function wbTree(){const d=s.doc.data;return group('등록 객체')+d.nodes.map(n=>tree(n.name,'wbnode:'+n.id,META[n.kind]?.icon||'◇','r'+n.revision)).join('')+group('연결')+d.links.map(l=>tree((wbNode(l.from)?.name||'?')+' → '+(wbNode(l.to)?.name||'?'),'wblink:'+l.id,'↗',wbStale(l))).join('');}
  function wbHead(){const d=s.doc.data;return docHeader(s.doc.title,'시스템 연결',`${pill(d.nodes.length+' 객체')} ${pill(d.links.filter(x=>wbStale(x)!=='current').length+' 주의',d.links.some(x=>wbStale(x)!=='current')?'warn':'good')}`);}
  function wbGraph(){const d=s.doc.data;const get=key=>d.nodes.find(x=>x.id===key);return `<div class="canvas-frame" style="height:460px;min-height:460px"><div class="canvas-toolbar"><b>프로젝트 연결도</b><span class="spacer"></span>${btn('객체 등록','register')}${btn('포트 연결','connect')}${btn('최신 revision 확인','refresh')}</div><div style="height:414px;position:relative">${`<svg class="edge-layer" viewBox="0 0 900 414" preserveAspectRatio="none">${d.links.map(l=>{const a=get(l.from),b=get(l.to);if(!a||!b)return '';const x1=(a.x/100*900)+115,y1=a.y/100*414+30,x2=b.x/100*900,y2=b.y/100*414+30;return `<path data-select="wblink:${l.id}" class="${wbStale(l)} ${s.selection==='wblink:'+l.id?'active':''}" d="M${x1},${y1} C${x1+90},${y1} ${x2-90},${y2} ${x2},${y2}"><title>${esc(wbStale(l))}</title></path>`}).join('')}</svg>`}${d.nodes.map(n=>`<div class="node ${s.selection==='wbnode:'+n.id?'active':''}" data-select="wbnode:${n.id}" data-open-node="${n.id}" style="left:${n.x}%;top:${n.y}%;transform:translateY(-50%)"><b>${esc(META[n.kind]?.icon||'◇')} ${esc(n.name)}</b><div class="mono">${esc(META[n.kind]?.name||n.kind)} · r${n.revision}</div><div class="ports"><span><i class="dot"></i> 입력</span><span>출력 <i class="dot"></i></span></div></div>`).join('')}</div><div class="canvas-note">노드를 두 번 클릭하면 등록된 정확한 문서 ID/revision을 해당 프로그램에서 엽니다.</div></div>`;}
  function wbStage(){const d=s.doc.data;return `<div class="stack">${wbGraph()}${d.nodes.length?`<div class="table-wrap"><table><thead><tr><th>연결</th><th>저장 입력 버전</th><th>상태</th><th>동작</th></tr></thead><tbody>${d.links.map(l=>`<tr class="clickable ${s.selection==='wblink:'+l.id?'active':''}" data-select="wblink:${l.id}"><td>${esc(wbNode(l.from)?.name||'파일 없음')} → ${esc(wbNode(l.to)?.name||'파일 없음')}</td><td>r${l.fromRevision}</td><td>${pill(wbStale(l),wbStale(l)==='current'?'good':'warn')}</td><td>이전 결과 보존</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">독립 앱에서 저장한 문서를 등록하면 시스템 연결도를 구성할 수 있습니다.</div>'}</div>`;}
  function wbInspector(){const d=s.doc.data,key=s.selection;if(key.startsWith('wbnode:')){const n=wbNode(key.slice(7));if(!n)return '';const latest=s.docs.find(x=>x.id===n.docId);return `<div class="inspector-title">${esc(n.name)}</div>${propGroup('등록 객체',row('프로그램',META[n.kind]?.name||n.kind)+row('객체 ID',n.docId)+row('고정 버전','r'+n.revision)+row('현재 버전',latest?'r'+latest.revision:'찾을 수 없음'))}${btn('해당 프로그램에서 열기','open-node','class="primary"')}${btn('등록 버전을 최신으로','update-node')}`;}
    if(key.startsWith('wblink:')){const l=d.links.find(x=>x.id===key.slice(7));if(!l)return '';return `<div class="inspector-title">연결 ${esc(l.id)}</div>${propGroup('입출력 계약',row('출발',wbNode(l.from)?.name||'없음')+row('도착',wbNode(l.to)?.name||'없음')+row('원본 revision','r'+l.fromRevision)+row('상태',wbStale(l)))+note('입력 파일을 수정하면 이 연결은 갱신 필요가 됩니다. 기존 실행 결과는 삭제하지 않습니다.',wbStale(l)==='current'?'':'warn')}${btn('새 입력 revision 연결','refresh-link')}`;}
    return `<div class="inspector-title">프로젝트</div>${propGroup('저장',row('객체',d.nodes.length)+row('연결',d.links.length)+row('저장 파일',s.doc.id+'.caeproject'))}${note('이 프로젝트는 참조와 연결만 소유합니다. 각 앱의 문서는 독립 파일입니다.')}`;}
  function wbDock(){if(!s.doc||APP!=='workbench')return '';const d=s.doc.data;return `<div class="dock-line">연결 오류 ${d.links.filter(x=>wbStale(x)==='broken').length} · 갱신 필요 ${d.links.filter(x=>wbStale(x)==='stale').length}</div><div class="dock-line">링크의 입력 revision은 저장 시 고정되며 자동 재계산하지 않습니다.</div>`;}

  function listDialog(kind,act,title){const docs=s.docs.filter(x=>!kind||x.kind===kind);modal(`<h2>${esc(title)}</h2>${docs.length?`<div class="recent">${docs.map(d=>`<button data-act="${act}" data-doc-id="${d.id}"><strong>${esc(d.title)}</strong><small>${esc(META[d.kind]?.name||d.kind)} · r${d.revision} · ${esc(d.updatedAt||'')}</small></button>`).join('')}</div>`:'<div class="empty">선택 가능한 저장 파일이 없습니다.</div>'}<div class="dialog-actions">${btn('닫기','dismiss')}</div>`);}
  function parseDelimited(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw new Error('숫자 데이터가 두 행 이상 필요합니다.');const comma=lines[0].includes(','),sep=comma?',':lines[0].includes('\t')?'\t':/;/.test(lines[0])?';':null;const rows=lines.map(line=>sep?line.split(sep).map(x=>x.trim()):line.trim().split(/\s+/));const header=rows[0].some(x=>Number.isNaN(Number(x)))?rows.shift():rows[0].map((_,i)=>'열 '+(i+1));return {rows,header,separator:sep||'space'};}
  function filePicker(mode){const input=document.createElement('input');input.type='file';input.accept=mode==='obj'?'.obj':'.csv,.txt,.dat,.asc';input.onchange=async()=>{if(!input.files?.length)return;const file=input.files[0];if(file.size>2*1024*1024){failure(new Error('시안의 파일 입력은 2 MiB 이하입니다.'));return;}try{const raw=await file.text();if(mode==='obj'){importObj(raw,file.name);return;}const parsed=parseDelimited(raw);s.live.import={mode,name:file.name,raw,...parsed};if(APP==='opt'){modal(`<h2>${esc(file.name)} 후보 표</h2>${note('헤더 E, rmse가 있는 실제 선택 파일을 읽습니다. 파일 값은 “가져온 값”으로 보존하며 solver 실행 여부를 추정하지 않습니다.')}<div class="mono" style="max-height:150px;overflow:auto;white-space:pre-wrap">${esc(parsed.header.join(' | ')+'\n'+parsed.rows.slice(0,5).map(r=>r.join(' | ')).join('\n'))}</div><div class="dialog-actions">${btn('취소','dismiss')}${btn('후보 가져오기','confirm-candidates','class="primary"')}</div>`);return;}const opts=parsed.header.map((h,i)=>`<option value="${i}">${esc(h)}</option>`).join('');modal(`<h2>${esc(file.name)} 열 매핑</h2>${note('실제 선택한 파일의 앞부분을 읽었습니다. 원본 텍스트와 매핑을 문서에 저장합니다.')}<div class="mono" style="max-height:110px;overflow:auto;white-space:pre-wrap">${esc(parsed.rows.slice(0,4).map(r=>r.join(' | ')).join('\n'))}</div><div class="grid2"><label>X / 축 열<select id="import-x">${opts}</select></label><label>Y / 응답 열<select id="import-y">${opts}</select></label></div><div class="grid2"><label>X 단위<input id="import-x-unit" value="s"></label><label>Y 단위<input id="import-y-unit" value="${APP==='pre'?'MPa':'N'}"></label></div><div class="dialog-actions">${btn('취소','dismiss')}${btn('매핑 확정','confirm-import','class="primary"')}</div>`);el('import-y').value=String(Math.min(1,parsed.header.length-1));}catch(error){failure(error);}};input.click();}
  function confirmCandidates(){const info=s.live.import;if(!info)return;const cols=info.header.map(x=>x.trim().toLowerCase()),eIdx=cols.findIndex(x=>/^e$|modulus/.test(x)),rIdx=cols.findIndex(x=>/rmse|objective/.test(x));if(eIdx<0||rIdx<0)throw new Error('후보 CSV는 E와 rmse 헤더가 필요합니다.');const records=info.rows.map((row,i)=>({E:Number(row[eIdx]),rmse:Number(row[rIdx]),row:i+2}));for(const x of records)if(!Number.isFinite(x.E)||!Number.isFinite(x.rmse))throw new Error(`행 ${x.row}의 E 또는 rmse가 숫자가 아닙니다.`);mutate(d=>{for(const x of records)d.candidates.push({id:id('import-'),E:x.E,rmse:x.rmse,cost:0,actual:true,source:info.name,sourceRow:x.row});d.importedCandidateSource={name:info.name,raw:info.raw};},`${info.name}에서 후보 ${records.length}개를 가져왔습니다.`);dismiss();}
  function importObj(raw,name){const verts=[],faces=[];for(const line of raw.split(/\r?\n/)){const bits=line.trim().split(/\s+/);if(bits[0]==='v'&&bits.length>=4)verts.push(bits.slice(1,4).map(Number));if(bits[0]==='f'&&bits.length>=4){const ids=bits.slice(1).map(x=>Number(x.split('/')[0])-1);for(let j=1;j<ids.length-1;j++)faces.push([ids[0],ids[j],ids[j+1]]);}}if(!verts.length||!faces.length)throw new Error('OBJ에 vertex와 face가 필요합니다.');if(verts.some(v=>v.some(x=>!Number.isFinite(x)))||faces.some(f=>f.some(i=>i<0||i>=verts.length)))throw new Error('OBJ의 좌표 또는 면 참조가 잘못됐습니다.');const mins=[0,1].map(k=>Math.min(...verts.map(v=>v[k]))),maxs=[0,1].map(k=>Math.max(...verts.map(v=>v[k])));const projected=verts.map(v=>[(v[0]-mins[0])/(maxs[0]-mins[0]||1),(v[1]-mins[1])/(maxs[1]-mins[1]||1)]);mutate(d=>{d.vertices=projected;d.mesh=faces;d.meshName=name;d.meshRaw=raw;d.mode='mesh';d.source=name;},'실제 OBJ 파일을 읽어 '+faces.length+'개 면을 만들었습니다. 저장하세요.');}
  function confirmImport(){const info=s.live.import;if(!info)return;const ix=Number(el('import-x').value),iy=Number(el('import-y').value),unitX=el('import-x-unit').value.trim(),unitY=el('import-y-unit').value.trim();if(ix===iy||!unitX||!unitY){notify('서로 다른 축/응답 열과 단위가 필요합니다.','bad');return;}const points=[];for(let i=0;i<info.rows.length;i++){const row=info.rows[i],x=Number(row[ix]),y=Number(row[iy]);if(!Number.isFinite(x)||!Number.isFinite(y))throw new Error(`행 ${i+1}의 선택한 열이 숫자가 아닙니다.`);if(points.length&&x<points.at(-1)[0])throw new Error(`행 ${i+1}의 축 값이 이전 행보다 작습니다.`);points.push([x,y]);}if(APP==='pre')mutate(d=>{d.points=points;d.intervals=[];d.conditions=[];d.source=info.name;d.unitX=unitX;d.unitY=unitY;d.rawSource=info.raw;d.columnMapping={x:ix,y:iy,separator:info.separator};d.mode='curve';},`${info.name}에서 ${points.length}개 점을 가져왔습니다. 저장하세요.`);else if(APP==='post')mutate(d=>{const newId=id('result-');d.datasets.push({id:newId,name:info.name,source:info.name,kind:'curve',unit:unitY,axisName:'시간 ['+unitX+']',curve:points,rawSource:info.raw,columnMapping:{x:ix,y:iy,separator:info.separator}});d.selectedDataset=newId;d.compareId='';},`${info.name}에서 ${points.length}개 결과 표본을 가져왔습니다. 저장하세요.`);else if(APP==='opt'){const cols=info.header.map(x=>x.toLowerCase());const eIdx=cols.findIndex(x=>/^e$|modulus/.test(x)),rIdx=cols.findIndex(x=>/rmse|objective/.test(x));if(eIdx<0||rIdx<0)throw new Error('후보 CSV는 E와 rmse 열 이름이 필요합니다.');mutate(d=>{for(const row of info.rows){const E=Number(row[eIdx]),rmse=Number(row[rIdx]);if(!Number.isFinite(E)||!Number.isFinite(rmse))continue;d.candidates.push({id:id('import-'),E,rmse,cost:0,actual:true,source:info.name});}},'후보 CSV의 실제 값으로 표시했습니다.');}dismiss();}

  async function createLinkedPost(sourceName,curve,sourceRef){const data=initial('post');const rid=id('result-');data.datasets=[{id:rid,name:sourceName,source:'시연 실행 '+sourceRef,kind:'curve',unit:'1',axisName:'반복',curve:curve||[]}];data.selectedDataset=rid;const doc=await api('/api/docs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'post',title:sourceName+' · 후처리',data})});window.open('/post?id='+doc.id+'&revision='+doc.revision,'_blank');notify('후처리 문서를 별도 파일로 만들었습니다.');}
  async function demoRun(){const d=s.doc.data,c=d.cases[0];if(!c){notify('케이스가 없습니다.','bad');return;}const r={id:id('run-'),name:'시연 실행 '+(d.runs.length+1),caseId:c.id,inputId:c.sourceId||s.doc.id,inputRevision:c.sourceRevision||s.doc.revision,backend:c.backend,status:'queued',startedAt:new Date().toISOString(),log:['[queue] 고정 입력 revision '+(c.sourceRevision||s.doc.revision),'[demo] 실제 solver를 호출하지 않습니다.'],convergence:[[0,1]],reason:''};mutate(x=>{x.runs.push(r);x.selectedRun=r.id;},'시연 실행을 큐에 넣었습니다.');s.selection='run:'+r.id;await saveDoc();setTimeout(async()=>{if(s.doc?.data.runs.find(x=>x.id===r.id)?.status!=='queued')return;mutate(x=>{const run=x.runs.find(y=>y.id===r.id);run.status='running';run.log.push('[demo] 입력 snapshot으로 시연 진행');run.convergence=[[0,1],[1,.4],[2,.15]];});await saveDoc();},500);setTimeout(async()=>{if(s.doc?.data.runs.find(x=>x.id===r.id)?.status!=='running')return;mutate(x=>{const run=x.runs.find(y=>y.id===r.id);run.status='done';run.log.push('[demo] 시연 수렴 완료 · 제품 solver 결과 아님');run.convergence=[[0,1],[1,.4],[2,.15],[3,.045],[4,.012]];run.resultId=id('demo-result-');});await saveDoc();},1400);}
  async function registerDoc(docId){const item=s.docs.find(x=>x.id===docId);if(!item)return;const d=s.doc.data;const already=d.nodes.find(x=>x.docId===docId);if(already){notify('이미 등록한 객체입니다.');dismiss();return;}mutate(x=>x.nodes.push({id:id('node-'),docId:item.id,kind:item.kind,name:item.title,revision:item.revision,x:Math.min(74,8+x.nodes.length*22),y:24+(x.nodes.length%3)*23}),item.title+'을 등록했습니다. 저장하세요.');dismiss();}
  function connectDialog(){const d=s.doc.data;if(d.nodes.length<2){notify('연결하려면 저장된 객체를 두 개 이상 등록하세요.','warn');return;}const opts=d.nodes.map(n=>`<option value="${n.id}">${esc(n.name)} · ${esc(META[n.kind]?.name)}</option>`).join('');modal(`<h2>입출력 연결</h2><p>출발 문서의 저장 revision을 고정합니다. 변경 후 재계산은 수동으로 수행합니다.</p><div class="grid2"><label>출발 객체<select id="connect-from">${opts}</select></label><label>도착 객체<select id="connect-to">${opts}</select></label></div><div class="dialog-actions">${btn('취소','dismiss')}${btn('연결','confirm-connect','class="primary"')}</div>`);el('connect-to').selectedIndex=1;}
  function confirmConnect(){const from=el('connect-from').value,to=el('connect-to').value,d=s.doc.data,a=wbNode(from),b=wbNode(to);if(from===to){notify('같은 객체를 연결할 수 없습니다.','bad');return;}const allowed={pre:['runner','opt','post'],runner:['post','opt'],post:['opt','expert'],opt:['post','pre','expert'],expert:['opt','workbench']};if(!allowed[a.kind]?.includes(b.kind)){notify(`${META[a.kind].name} → ${META[b.kind].name} 포트 형식은 지원하지 않습니다.`,'bad');return;}if(d.links.some(x=>x.from===from&&x.to===to)){notify('이미 연결됐습니다.','warn');return;}const routes=d.links.map(x=>[x.from,x.to]);const reach=(start,target,seen=new Set())=>start===target||routes.filter(x=>x[0]===start&&!seen.has(x[1])).some(x=>reach(x[1],target,new Set([...seen,start])));if(reach(to,from)){notify('순환 연결은 허용하지 않습니다.','bad');return;}const latest=s.docs.find(x=>x.id===a.docId);mutate(x=>x.links.push({id:id('link-'),from,to,fromRevision:a.revision,fromHash:latest?.semanticHash||'',binding:'latest',port:'document'}),'연결했습니다. 출발 revision r'+a.revision+' 고정. 저장하세요.');dismiss();}

  async function action(act,target){
    if(document.querySelector('.menu-pop'))document.querySelector('.menu-pop').remove();
    if(act==='new')return createDoc();
    if(act==='confirm-new')return confirmNew();
    if(act==='discard-new'){const title=s.live.pendingNewTitle;s.dirty=false;dismiss();return createDocNamed(title);}
    if(act==='save-new'){const title=s.live.pendingNewTitle;dismiss();await saveDoc();if(!s.dirty)return createDocNamed(title);return;}
    if(act==='open')return listDialog(APP,'choose-open','저장된 '+META[APP].name+' 파일 열기');
    if(act==='choose-open'){dismiss();return openDoc(target.dataset.docId);}
    if(act==='discard-open'){const next=s.live.pendingOpen;s.dirty=false;dismiss();return openDoc(next.docId,next.revision);}
    if(act==='save-open'){const next=s.live.pendingOpen;dismiss();await saveDoc();if(!s.dirty)return openDoc(next.docId,next.revision);return;}
    if(act==='refresh')return loadList();
    if(act==='save')return saveDoc();
    if(act==='undo')return undo();
    if(act==='close')return closeDoc();
    if(act==='discard-close'){dismiss();return reallyClose();}
    if(act==='save-close'){dismiss();await saveDoc();if(!s.dirty)return reallyClose();return;}
    if(act==='dismiss')return dismiss();
    if(act==='switch-app'){window.open('/'+target.dataset.kind,'_blank');dismiss();return;}
    if(act==='reload-conflict'){const doc=s.live.conflict;dismiss();openDocObject(doc);notify('디스크의 최신 버전을 다시 열었습니다.');return;}
    if(act==='rename'){if(!s.doc)return;modal(`<h2>문서 이름 변경</h2><label>새 이름<input id="rename-title" maxlength="120" value="${esc(s.doc.title)}"></label><div class="dialog-actions">${btn('취소','dismiss')}${btn('적용','confirm-rename','class="primary"')}</div>`);el('rename-title').focus();return;}
    if(act==='confirm-rename'){const title=el('rename-title')?.value.trim();if(!title){notify('문서 이름을 입력하세요.','bad');return;}s.doc.title=title;s.dirty=true;dismiss();render();return;}
    if(act==='toggle-tree'){document.body.classList.toggle('hide-tree');return;}
    if(act==='toggle-inspector'){document.body.classList.toggle('hide-inspector');return;}
    if(act==='toggle-dock'){el('dock').classList.toggle('collapsed');return;}
    if(act==='clear-selection'){s.selection='';render();return;}
    if(act==='about')return modal(`<h2>설계 검증 시안</h2>${note('파일 생성·저장·revision 충돌·선택 연동·외부 CSV/OBJ 입력은 실제로 동작합니다. 시연 계산과 전문가 응답은 제품 엔진/LLM이 아닙니다.','warn')}<p>데이터는 로컬 server.py의 user-data 폴더에 JSON 파일로 저장됩니다.</p><div class="dialog-actions">${btn('닫기','dismiss')}</div>`);
    if(act==='export-json'){if(!s.doc)return;window.open('/api/docs/'+s.doc.id+'/export','_blank');return;}
    if(!s.doc)return;
    const d=s.doc.data;
    if(act==='validate'||act==='validate-case'){const errors=validate(s.doc);notify(errors.length?errors.join(' / '):'기본 입력 검증 통과 · 물리 검증과 backend 준비는 별도입니다.',errors.length?'bad':'');return;}
    if(act==='csv-import'||act==='candidate-import')return filePicker('csv');
    if(act==='obj-import')return filePicker('obj');
    if(act==='confirm-import')return confirmImport();
    if(act==='confirm-candidates')return confirmCandidates();
    if(act==='view-curve'||act==='view-mesh')return mutate(x=>x.mode=act==='view-curve'?'curve':'mesh');
    if(act==='add-point'){const last=d.points.at(-1)||[0,0];mutate(x=>x.points.push([Number(last[0])+0.2,Number(last[1])]),'곡선 점을 추가했습니다.');s.selection='point:'+(d.points.length-1);render();return;}
    if(act==='add-interval'){const lo=d.points[0]?.[0]||0,hi=d.points.at(-1)?.[0]||1,a={id:id('seg-'),name:'새 구간',start:lo,end:hi,weight:1};mutate(x=>x.intervals.push(a),'구간을 추가했습니다.');s.selection='interval:'+a.id;render();return;}
    if(act==='add-condition'){const selected=s.selection.startsWith('interval:')?s.selection.slice(9):'';const a={id:id('cond-'),name:'새 조건',target:selected||d.intervals[0]?.id||'',value:1,unit:'mm/s'};mutate(x=>x.conditions.push(a),'조건을 추가했습니다.');s.selection='cond:'+a.id;render();return;}
    if(act==='delete-selected'){const key=s.selection;if(!key){notify('먼저 대상이나 노드를 선택하세요.','warn');return;}mutate(x=>{if(key.startsWith('point:'))x.points.splice(Number(key.slice(6)),1);else if(key.startsWith('interval:'))x.intervals=x.intervals.filter(v=>v.id!==key.slice(9));else if(key.startsWith('cond:'))x.conditions=x.conditions.filter(v=>v.id!==key.slice(5));else if(key.startsWith('node:')){x.nodes=x.nodes.filter(v=>v.id!==key.slice(5));x.edges=x.edges.filter(v=>!v.includes(key.slice(5)));}},'선택 대상을 삭제했습니다.');s.selection='';render();return;}
    if(act==='send-runner'){if(s.dirty)await saveDoc();if(s.dirty)return;const data=initial('runner');data.cases=[{id:'case-1',name:s.doc.title,sourceId:s.doc.id,sourceRevision:s.doc.revision,backend:'시연 계산기',valid:true}];const doc=await api('/api/docs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'runner',title:s.doc.title+' · 실행',data})});window.open('/runner?id='+doc.id+'&revision='+doc.revision,'_blank');notify('실행기 파일을 만들고 입력 revision을 고정했습니다.');return;}
    if(act==='link-case')return listDialog('pre','choose-case','전처리 파일을 입력으로 연결');
    if(act==='choose-case'){const src=s.docs.find(x=>x.id===target.dataset.docId);if(!src)return;mutate(x=>{if(APP==='runner'){x.cases[0].sourceId=src.id;x.cases[0].sourceRevision=src.revision;x.cases[0].name=src.title;}else{x.sourceId=src.id;x.sourceRevision=src.revision;}},'입력 '+src.title+' r'+src.revision+'을 고정했습니다.');dismiss();return;}
    if(act==='run')return demoRun();
    if(act==='cancel-run'){const r=selectedRun();if(!r||!['queued','running'].includes(r.status)){notify('실행 중인 작업이 없습니다.','warn');return;}mutate(x=>{const run=x.runs.find(y=>y.id===r.id);run.status='cancelled';run.reason='사용자 중단 · 시연';run.log.push('[demo] 중단 요청을 확인해 종료했습니다.');},'시연 실행을 중단했습니다.');return saveDoc();}
    if(act==='retry-run')return demoRun();
    if(act==='send-post'){if(APP==='runner'){const r=selectedRun();if(!r||r.status!=='done'){notify('완료한 실행을 선택하세요.','warn');return;}return createLinkedPost(r.name,r.convergence,r.id);}const c=d.candidates.find(x=>x.id===d.selectedCandidate);return createLinkedPost(c?.id||'후보',[[0,.4],[1,.2],[2,c?.rmse||.1]],c?.id||'시연 후보');}
    if(act==='compare'){if(!d.compareId){notify('비교 결과를 선택하세요.','warn');return;}notify('선택한 결과 두 개를 중앙 곡선에 표시합니다.');render();return;}
    if(act==='export-csv'){const r=currentDataset();if(!r)return;const rows=r.kind==='field'?fieldValues(r,d).map((v,i)=>[i+1,v]):r.curve||[];const csv=(r.kind==='field'?'location,value':'axis,value')+'\n'+rows.map(p=>p.join(',')).join('\n')+'\n';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=(r.name||'extract').replace(/\.csv$/i,'')+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);notify('현재 표시 결과를 CSV로 추출했습니다.');return;}
    if(act==='add-variable'){const v={id:id('v-'),name:'새 변수',unit:'1',lo:0,hi:1};mutate(x=>x.variables.push(v),'변수를 추가했습니다.');s.selection='variable:'+v.id;render();return;}
    if(act==='add-node'){const n={id:id('step-'),type:'변환',x:40,y:75};mutate(x=>x.nodes.push(n),'절차 노드를 추가했습니다.');s.selection='node:'+n.id;render();return;}
    if(act.startsWith('opt-view-')){s.view=act.slice(9);d.views.optView=s.view;s.dirty=true;render();return;}
    if(act==='doe'){mutate(x=>{for(let i=0;i<3;i++){const E=600+(x.candidates.length+i)*95; x.candidates.push({id:id('demo-'),E,rmse:Number((.2-Math.min(E,1300)/10000).toFixed(3)),cost:40+i*12,actual:false,source:'시연 DOE'});}},'시연 후보 3개를 만들었습니다. 실제 평가 결과가 아닙니다.');return;}
    if(act==='pareto'){s.view='space';render();notify('설계 공간에서 RMSE와 E 위치로 후보를 탐색합니다. 노랑 점은 시연 값입니다.');return;}
    if(act==='candidate-compare'){s.view='compare';render();return;}
    if(act==='send-pre'){if(!d.sourceId){notify('이 연구에 연결된 전처리 객체가 없습니다.','warn');return;}window.open('/pre?id='+d.sourceId+'&revision='+d.sourceRevision,'_blank');return;}
    if(act==='send-message'){const input=el('compose'),text=input?.value.trim();if(!text){notify('보낼 내용을 입력하세요.','warn');return;}const reply=s.selection.startsWith('message:')?s.selection.slice(8):null;const m={id:id('m-'),role:'user',who:'사용자',text,replyTo:reply,sources:[]};mutate(x=>{x.messages.push(m);if(x.issues.length)x.issues[0].messageIds.push(m.id);},'사용자 발언을 타임라인에 기록했습니다. 저장하세요.');s.selection='message:'+m.id;render();el('timeline')?.scrollTo(0,el('timeline').scrollHeight);return;}
    if(act==='demo-reply'){if(d.paused){notify('일시중지 중입니다. 이어가기 후 시연 응답을 생성하세요.','warn');return;}const user=[...d.messages].reverse().find(x=>x.role==='user');if(!user)return;const count=d.demoReplyCount+1,m={id:id('m-'),role:'demo',who:count%2?'재료 전문가 · 시연':'해석 전문가 · 시연',text:count%2?'새 관측을 반영해 시험 속도와 재료 속도 의존성을 분리 검토하겠습니다. 실제 LLM 응답이 아닙니다.':'경계조건과 접촉 이력을 대조해야 합니다. 현재 정보로 원인을 확정할 수 없습니다. 실제 LLM 응답이 아닙니다.',replyTo:user.id,sources:[]};mutate(x=>{x.demoReplyCount=count;x.messages.push(m);if(x.issues.length)x.issues[0].messageIds.push(m.id);},'선택한 사용자 발언에 연결된 시연 응답을 추가했습니다.');s.selection='message:'+m.id;render();el('timeline')?.scrollTo(0,el('timeline').scrollHeight);return;}
    if(act==='pause')return mutate(x=>x.paused=!x.paused,d.paused?'이어갔습니다.':'일시중지했습니다.');
    if(act==='add-issue'){modal(`<h2>논점 추가</h2><label>논점 이름<input id="issue-name" maxlength="120" value="새 논점"></label><div class="dialog-actions">${btn('취소','dismiss')}${btn('논점 만들기','confirm-issue','class="primary"')}</div>`);el('issue-name').focus();return;}
    if(act==='confirm-issue'){const name=el('issue-name')?.value.trim();if(!name){notify('논점 이름을 입력하세요.','bad');return;}mutate(x=>x.issues.push({id:id('issue-'),name,status:'미해결',messageIds:[]}),name+' 논점을 만들었습니다.');dismiss();return;}
    if(act==='link-evidence')return listDialog(null,'choose-evidence','저장된 근거 파일 연결');
    if(act==='choose-evidence'){const src=s.docs.find(x=>x.id===target.dataset.docId);mutate(x=>x.evidence.push({id:id('ev-'),name:src.title,docId:src.id,revision:src.revision}),'근거 ID/revision을 고정했습니다.');dismiss();return;}
    if(act==='open-evidence'){const e=d.evidence.find(x=>x.id===s.selection.slice(9));if(e){const src=s.docs.find(x=>x.id===e.docId);window.open('/'+src.kind+'?id='+e.docId+'&revision='+e.revision,'_blank');}return;}
    if(act==='jump-reply'){const m=d.messages.find(x=>x.id===s.selection.slice(8));if(m?.replyTo){s.selection='message:'+m.replyTo;render();}return;}
    if(act==='reply-to'){el('compose')?.focus();return;}
    if(act==='register')return listDialog(null,'choose-register','저장 객체 등록');
    if(act==='choose-register')return registerDoc(target.dataset.docId);
    if(act==='connect')return connectDialog();
    if(act==='confirm-connect')return confirmConnect();
    if(act==='open-node'){const n=wbNode(s.selection.slice(7));if(n)window.open('/'+n.kind+'?id='+n.docId+'&revision='+n.revision,'_blank');return;}
    if(act==='update-node'){const n=wbNode(s.selection.slice(7)),latest=s.docs.find(x=>x.id===n?.docId);if(!n||!latest)return;mutate(x=>{const item=x.nodes.find(y=>y.id===n.id);item.revision=latest.revision;item.name=latest.title;},'등록 객체를 최신 revision으로 가리킵니다. 과거 링크는 보존됩니다.');return;}
    if(act==='refresh-link'){const l=d.links.find(x=>x.id===s.selection.slice(7)),a=wbNode(l?.from),latest=s.docs.find(x=>x.id===a?.docId);if(!latest)return;mutate(x=>{const link=x.links.find(y=>y.id===l.id);link.fromRevision=latest.revision;link.fromHash=latest.semanticHash||'';},'새 입력 revision을 이 연결에 적용했습니다. 과거 실행은 그대로 보존됩니다.');return;}
    if(act==='impact'){const stale=d.links.filter(x=>wbStale(x)!=='current');notify(stale.length?`${stale.length}개 연결이 갱신 필요 또는 누락입니다.`:'등록 연결은 최신 revision을 가리킵니다.',stale.length?'warn':'');return;}
  }

  document.addEventListener('click', async event=>{
    const menu=event.target.closest('[data-menu]');if(menu){popMenu(menu.dataset.menu,menu);return;}
    const open=event.target.closest('[data-open]');if(open){await openDoc(open.dataset.open);return;}
    const selectTarget=event.target.closest('[data-select]');if(selectTarget){const key=selectTarget.dataset.select;if(APP==='post'&&key.startsWith('dataset:')){mutate(d=>d.selectedDataset=key.slice(8));s.selection=key;render();return;}if(APP==='post'&&key.startsWith('cell:')){mutate(d=>{d.location=Number(key.slice(5));d.views.selection=key;});s.selection=key;render();return;}if(APP==='opt'&&key.startsWith('candidate:')){s.view='space';mutate(d=>{d.selectedCandidate=key.slice(10);d.views.optView='space';});s.selection=key;render();return;}if(APP==='opt'&&key.startsWith('node:'))s.view='workflow';s.selection=key;render();return;}
    const command=event.target.closest('[data-act]');if(command){try{await action(command.dataset.act,command);}catch(error){failure(error);}return;}
    if(!event.target.closest('.menu-pop'))document.querySelector('.menu-pop')?.remove();
  });
  document.addEventListener('dblclick', event=>{const target=event.target.closest('[data-open-node]');if(target){s.selection='wbnode:'+target.dataset.openNode;action('open-node',target).catch(failure);}});
  document.addEventListener('focusin',event=>{if(event.target.dataset.field&&event.target.matches('input,textarea'))s.live.editingField={element:event.target,snapshot:clone(s.doc?.data),before:event.target.value};});
  document.addEventListener('input',event=>{if(event.target.dataset.field&&event.target.matches('input,textarea'))fieldInput(event.target);});
  document.addEventListener('focusout',event=>{const editing=s.live.editingField;if(editing?.element===event.target){s.live.editingField=null;if(event.target.value!==editing.before){s.undo.push(editing.snapshot);if(s.undo.length>40)s.undo.shift();notify('속성을 수정했습니다. 저장하면 새 revision이 됩니다.');setTimeout(refreshEditedView,0);}}});
  document.addEventListener('change',event=>{if(event.target.dataset.field&&event.target.matches('select,input[type=checkbox]'))fieldChange(event.target);});
  document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();saveDoc();}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();undo();}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='o'){event.preventDefault();listDialog(APP,'choose-open','저장 파일 열기');}});
  el('open-launcher').onclick=()=>closeDoc();
  el('app-switch').onclick=()=>modal(`<h2>독립 프로그램 열기</h2><div class="recent">${Object.entries(META).map(([kind,m])=>`<button data-act="switch-app" data-kind="${kind}"><strong>${m.icon} ${esc(m.name)}</strong><small>${esc(m.sub)}</small></button>`).join('')}</div><div class="dialog-actions">${btn('닫기','dismiss')}</div>`);
  el('tree-collapse').onclick=()=>document.body.classList.toggle('hide-tree');
  el('inspector-collapse').onclick=()=>document.body.classList.toggle('hide-inspector');
  el('dock-toggle').onclick=()=>el('dock').classList.toggle('collapsed');
  window.addEventListener('beforeunload',event=>{if(s.dirty){event.preventDefault();event.returnValue='';}});
  (async()=>{await loadList();const params=new URLSearchParams(location.search);if(params.has('id'))await openDoc(params.get('id'),params.get('revision'));else render();})();
})();
